### PR TITLE
Sounds when someone warn a player

### PR DESCRIPTION
**Pull request by RubeVi**
i forgot to add the import in the last PR

### CODE REVIEW

**Comment by Alfalik** [comment]
What if I have the sounds disabled?

**Comment by dentmaged** [comment]
@Alfalik You can say the same about /toggle sounds.

**Comment by Alfalik** [comment]
@dentmaged I mean /toggle sounds, sorry if I didn't be clear.

**Comment by dentmaged** [comment]
@Alfalik You will still hear the sound even if sounds are disabled (/toggle Sounds - not Minecraft sounds).

**Comment by Alfalik** [comment]
@dentmaged I know what ```/toggle sounds``` does
@RubeVi The code should be:

```
for (Player player : Bukkit.getOnlinePlayers()) {
     if (Settings.getSettingByName("Sounds") != null && Settings.getSettingByName("Sounds").getValueByPlayer(player).getValue().equalsIgnoreCase("on")) {
          warned.playSound(warned.getLocation(), Sound.ENDERDRAGON_GROWL, 1.0, 2.0);
     }
}
```

**Comment by dentmaged** [comment]
@Alfalik Why? A player might not hear or see the warning.

**Comment by twizmwazin** [comment]
This sound, like others, should be toggleable.

**Comment by SungMatt** [comment]
It should be toggleable, but last time I was warned I knew I toggled sounds off, but yet it still played for me. Not sure what the current situation is like though, haven't been warned in a while.

**Comment by CaptainElliott** [comment]
@Alfalik there is no need to cycle through all of the online players... it is only being played to the warned player

**Comment by Alfalik** [comment]
@CaptainElliott Why don't you add it if you know how?

**Comment by dentmaged** [comment]
@CaptainElliott Where is he doing that?

**Comment by iEli2tyree011** [comment]
@RubeVi Do you plan to make this sound toggleable?

**Comment by RubeVi** [comment]
No, i don't

**Comment by twizmwazin** [comment]
@RubeVi That's an issue, it needs to be togglable

**Comment by RubeVi** [comment]
Why this need be togglable?

**Comment by iEli2tyree011** [comment]
@RubeVi Because some players don't like to hear sounds and toggle them using /toggle sounds.

**Comment by RubeVi** [comment]
Well no problem, merge and make this togglable, because i don't know how to do that

**Comment by Alfalik** [comment]
@iEli2tyree011 @RubeVi I already made it toggleable in #674, just saying.

**Comment by iEli2tyree011** [comment]
Since this wasn't made toggleable, it'd be better to merge #674 since it has added these sounds with the toggle function in place already.

**Pull request closed without merging**
