### PR TITLE
Update Touch and Complete monument messages

### PR DESCRIPTION
**Pull request by Pablete1234**
PGM: http://gyazo.com/8a28b19ff352e6085ca51c5a01a702c2
Cardinal: http://gyazo.com/bf52e2a44c8f4a4446b47dfbe30e73d3

Cardinal after the commit: http://gyazo.com/879feec58ab110c8225d0e57c491423b

### CODE REVIEW

**Comment by TiTo-418** [comment]
Do this in one commit

**Comment by Pablete1234** [comment]
how do i change that?

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/pull/732

**Comment by twizmwazin** [comment]
@Pablete1234 Please don't use the github editor

**Comment by Pablete1234** [comment]
poor github editor, you will hurt it's feelings :c

**Comment by twizmwazin** [comment]
It's feelings should be hurt

**Comment by Pablete1234** [comment]
does it deserve it so badly?

**Comment by twizmwazin** [comment]
https://git-scm.com/

**Comment by Pablete1234** [comment]
i already have that installed to download and build... still, how should i upload using that?

**Comment by twizmwazin** [comment]
`git add -A`
`git commit -m 'Descriptive message here'`
`git push https://github.com/Pablete1234/CardinalPGM.git branch-name`

**Comment by Pablete1234** [comment]
twiz, either merge this one, or tito's one, i tried to do what you said, didn't quite work

**Pull request closed without merging**
