### PR TITLE
Show server message in MOTD

### PR DESCRIPTION
**Pull request by twizmwazin**
I'm not really sure exactly how people want this, so I'm going to give you guys a chance to comment on it. I like the implementation as is, let me know if you think it could be improved before this goes to master.

### CODE REVIEW

**Comment by TiTo-418** [comment]
Can you explain how it works please?

**Comment by twizmwazin** [comment]
Under the currently playing match message in the MOTD, you will see the server's set message, the same one that is displayed in the tab footer. This is intended just to display the server's owner or the team that owns the server. I have also lowered the event priority, meaning most other plugins which provide their own MOTDs can easily override Cardinal, so entirely custom MOTDs are easier.

**Comment by TiTo-418** [comment]
Is this toggeable?

**Comment by twizmwazin** [comment]
@TiTo-418 will implement

**Comment by TiTo-418** [comment]
Will be cool if you merge this after make it toggleable :D

**Comment by twizmwazin** [comment]
Since no one has any other feedback, I'll probably do that

**Comment by Alfalik** [comment]
@twizmwazin This should be fully toggleable, and use white or aqua color instead of dark gray. The colors even could be chosen in the config.

**Comment by twizmwazin** [comment]
Untested, but feel free to check that out. I think I got everyone's requests.

**Comment by TiTo-418** [comment]
It looks like this:
<a href="http://imgur.com/m840cfj"></a>

**Comment by TiTo-418** [comment]
I think this is ready to merge :D

**Comment by ryanw-se** [comment]
This looks solid, I agree with @TiTo-418 this could probably be landed.

**Comment by TiTo-418** [comment]
@twizmwazin You can delete the branch (The ranks branch too)

**Comment by twizmwazin** [comment]
@TiTo-418 don't worry about it

**Comment by TiTo-418** [comment]
@twizmwazin Ok

**Pull request merged**
