### PR TITLE
Fixing #1030

### PR DESCRIPTION
**Pull request by Prodigy4532**

### CODE REVIEW

**Comment by twizmwazin** [comment]
This isn't funny. From here forward, anyone who makes an issue or pull request regarding the developer list will be blocked from the repo.

**Comment by Pablete1234** [comment]
@twizmwazin can we keep the second part of the PR? (first you need it to compile tho)

**Comment by twizmwazin** [comment]
No. That's dumb.

**Comment by Pablete1234** [comment]
@twizmwazin I know, i was just joking

**Pull request closed without merging**
