### PR TITLE
Add /say & /broadcast commands

### PR DESCRIPTION
**Pull request by Alfalik**
Well, finally I got a little time to code something, here's the result.

### CODE REVIEW

**Comment by twizmwazin** [comment]
You need to register the class and add localization. Please do so and test this.

**Comment by Alfalik** [comment]
@twizmwazin Uh, my bad, forgot to register it, thanks for remember me. I'll add it in another PR to make one commit. Thanks again

**Comment by dentmaged** [comment]
@Alfalik twiz taught me this one but you can amend a commit!
```
git add aweseomfile.txt
git commit -m "Blah"
git push # Then you realise you forgot something
git add somefile.txt
git commit -m "Blah" --amend
git push
```
If ```git push``` tells you that you need to ```git pull```, run ```git push -f```` or ```git push --force```

Pretty easy! @twizmwazin is a master at git!

**Comment by Alfalik** [comment]
@dentmaged That's cool and useful. Thanks for the tip, but I can't try it because I actually deleted my fork.

**Comment by dentmaged** [comment]
@Alfalik That's a pain! Oh well!

**Pull request closed without merging**
