### PR TITLE
Add rank system

### PR DESCRIPTION
**Pull request by dentmaged**
Pretty easy to use! I hope this gets merged!

### CODE REVIEW

**Comment by RubeGamerV** [comment]
can you fork this in your repo? like dentmaged/CardinalPGM and merge your commit to can dowload this if you PR dosnt be merged

**Comment by Superjd10** [comment]
@RubeGamerV Hi,, my name is The Line Under The Title that says from where it's being merged, but if you don't see me, I am in https://github.com/anchor-dev/CardinalPGM/tree/Ranks 

FTR: 	dentmaged  wants to merge 1 commit into twizmwazin:master from **anchor-dev:Ranks**

**Comment by RubeGamerV** [comment]
if you create a rank, how do you add a player to the rank?. Like livestreamer, how do you add a player to livestreamer rank?

**Comment by TiTi-418** [comment]
@RubeGamerV I think in config.yml

**Comment by RubeGamerV** [comment]
@TiTi-418 ya hice un test y no me aparese esa opcion, solo me aparese para cambiar el color de la estrella y cosas asi como permisos

**Comment by TiTi-418** [comment]
@RubeGamerV Add a line under the rank: http://gyazo.com/82a653b35c0c5a96d3beaa3fb2f96c7f

**Comment by RubeGamerV** [comment]
Se borra la configuracion una vez que la pusiste

**Comment by RubeGamerV** [comment]
mira descargalo y testealo, aqui descargalo
https://github.com/anchor-dev/CardinalPGM/tree/Ranks

**Comment by TiTi-418** [comment]
@RubeGamerV Use /rank
@dentmaged Maybe you need better usages

**Comment by dentmaged** [comment]
/rank give <player> <rank>
/rank take <player> <rank>

Ranks are created in the config. Copy Moderator but make sure you change the values.

**Comment by TiTi-418** [comment]
@dentmaged After restart the server, the new lines erases

**Comment by dentmaged** [comment]
@TiTi-418 What new line?

**Comment by TiTi-418** [comment]
@dentmaged For example, the "livestramer" lines erases

**Comment by dentmaged** [comment]
Commit amended.

**Changelog:**
* Fixed bugs and saved config when a rank is added.
* Add a system to remove a permission, by adding a '-' in front of the permission node - useful for livestreamer ranks.

**Comment by dentmaged** [comment]
If @twizmwazin is unwilling to merge this, I'll begin work on Cardinal+. Which will have my two PRs and many other features. If anyone wants to help, feel free to make a PR. However, patience is a virtue.

**Comment by CaptainElliott** [comment]
@dentmaged if twiz won't merge this it's because he want's it done differently. So this **will** be added.

Also don't advertise your own forks without twiz's permission

**Comment by dentmaged** [comment]
@CaptainElliott What is wrong with #589 and this PR?

**Comment by CaptainElliott** [comment]
@dentmaged Twiz hasn't even looked at that....
and I gave you a reason for this. Twiz also  clearly stated that he may not merge it has he has in own implementations in mind

**Comment by dentmaged** [comment]
@CaptainElliott #589 was opened 5 days ago

**Comment by CaptainElliott** [comment]
@dentmaged and? he still hasn't looked at it and it hasn't been closed. Remember this is his project

**Comment by dentmaged** [comment]
@CaptainElliott Yes, I know this is his project. He last commited 2 days ago and I even pinged him and he still hasn't replied. I still haven't quite decided if I should begin work or not.

**Comment by CaptainElliott** [comment]
@dentmaged dude.... 2days is nothing, he is still active. I know he is working on quite a few things for Cardinal that are going to take time. You're writing code *expecting* for it to be implemented without regard for if he wants it to be coded the way you have or he wants it at all.

**Comment by dentmaged** [comment]
@CaptainElliott If he is active, how come he hasn't looked at #589?

**Comment by CaptainElliott** [comment]
@dentmaged he is too busy? Please just stop, it will be merged if twiz wants to. Stop trying to over complicate things. You have literally come in and hijacked this project, every issue or whatever you have attempted to fix and every idea you have attempted to implement without consulting him. Don't get me wrong this is great - your helping develop the plugin but don't get all annoyed when something **you** want is not done, twiz has made no promises merging what you have done, explicating saying "I make no guarantees that I will merge it" after saying that he was going to do it.
remember you are the one voluntarily writing code for him.

**Comment by CaptainElliott** [comment]
@dentmaged also his last commit was 19hours ago

**Comment by dentmaged** [comment]
@CaptainElliott How have I hijacked it? How many commits do I have? 13. And if I am hijacking this project then I better stop contributing to it. Good bye!

**Comment by CaptainElliott** [comment]
@dentmaged I think you misunderstood me. I'm saying that if you are going to voluntarily fix things and implement new features that people suggest you can't assume they will all be merged

**Comment by dentmaged** [comment]
@CaptainElliott Too late - already began work on setting up my fork :)

**Comment by dentmaged** [comment]
@CaptainElliott And I know my PRs may not be used but at least I'd like some feedback to know how I can improve - I am not too good at Java and I'm only 11.

**Comment by CaptainElliott** [comment]
@dentmaged that's fine (btw your code is pretty amazing if your an 11 year old, props), but complaining about something being merged is not the right attitude

**Comment by twizmwazin** [comment]
just to set things straight, I have been active, and dentmaged has messaged me on Skype. Even if I don't comment on a PR, it is generally safe to say that I will read it within 12 hours. If I'm not at school or sleeping, probably more like 1 hour. Even when I am not committing, I am frequently working behind the scenes in little ways.

Please keep in mind that this is my project. Anyone can make voluntary submissions through PRs, however it is entirely my final decision as to what gets merged and the direction of the project. Generally when deciding how to respond to a PR, the first thing I consider is trust. Some people I trust so well that I give them direct write access, as I feel they can make good decisions and will listen to me when I make a decision. When I have an implementation in mind for something, it will be extremely difficult to later win me over with another implementation.

**Comment by dentmaged** [comment]
@twizmwazin But then why don't you reply? If you don't like it, why don't you comment on it and close it?

**Comment by twizmwazin** [comment]
@dentmaged Because I want to see other people's opinions on it. While sometimes I don't immediately want something, Elly or Elliott_ may thing otherwise, and then we can discuss it. While I do get the final say, I am generally open to hearing what others have to say. Of course, when someone is particularly annoying on issues and in Skype, it makes his pull request approval much more likely to go 0 for 3.

**Comment by TiTi-418** [comment]
@Alfalik: "We aren't required to help developing the plugin and anyway, we do it. Besides, if they have a selfish mentality, isn't our fault."

**Comment by dentmaged** [comment]
@TiTi-418 What does @Alfalik have to do with this?

**Comment by TiTi-418** [comment]
https://github.com/twizmwazin/CardinalPGM/pull/542#issuecomment-89670933

**Pull request closed without merging**
