### PR TITLE
Ctf

### PR DESCRIPTION
**Pull request by Pablete1234**
This PR is alreay at the point where it can be used to play, works kinda bad, and has missing features, but the core and the scoreboard work well enough

ATM my testing maps are Desert Sanctuary and Nartica (my aim is to get that 2 maps working, and then fix any other features used by other maps)
To do:

- [x] Fix nets (on nartica, entering the net doesn't cap the flag)
- [x] Add all sounds
- [x] Fix particles
- [x] Fix the armor stand ontop of the flag (for some reason it doesn't spawn an armor stand)
- [x] Add flag filters

### CODE REVIEW

**Comment by SwiftGFX** [comment]
Where can I get these maps? I just want to test....

**Comment by twizmwazin** [comment]
We can't distribute maps here for copyright purposes. You'll need to aquire them on your own.

**Comment by SwiftGFX** [comment]
@twizmwazin Thanks! I'll check with other map

**Comment by SwiftGFX** [comment]
It works pretty good on The Last Sunset 2

**Comment by xFracTV** [comment]
Greenhouse CTF works

**Comment by Pablete1234** [comment]
I need help spawning the armor stand, for some wierd reason, https://github.com/twizmwazin/CardinalPGM/pull/960/files#diff-c4683c9cb7e9e0d50ece93880183f1e8R341 doesn't want to spawn an armor stand (if I uncomment the "bukkit.getConsol...." it returns "isDead: true"), so it's just like if it spawns dead already

**Comment by ryanwse** [comment]
Hey @Pablete1234, first of all thanks for your efforts to try and get this implemented. I tried it on a couple of CTF maps (Holo by NixaniaXi, and a few others) and was having issues getting them to work. I took a look at how Nartica implements its flags (nets & posts too) and copied that format into Holo, it worked perfectly!

I'd recommend expanding your test batch of CTF maps to reach more of the spectrum, as quite a few maps won't work out of the box, in their current state. Thanks again for your hard work!

**Comment by Pablete1234** [comment]
@ryanwse I know that, but i'm still working on desert sanctuary right now, adding filters for flags etc, after that, i will start looking into different maps's parsing and getting them to work

**Comment by ginie1** [comment]
apúrate a implementar esto, puto gordo

**Comment by Prodigy4532** [comment]
...

**Comment by TiTo-418** [comment]
```
[23:41:34 WARN]: java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Banner
[23:41:34 WARN]:        at in.twizmwaz.cardinal.module.modules.ctf.post.Post.<init>(Post.java:65)
[23:41:34 WARN]:        at in.twizmwaz.cardinal.module.modules.ctf.post.PostBuilder.parsePostElement(PostBuilder.java:69)
[23:41:34 WARN]:        at in.twizmwaz.cardinal.module.modules.ctf.FlagBuilder.getFlag(FlagBuilder.java:64)
[23:41:34 WARN]:        at in.twizmwaz.cardinal.module.modules.ctf.FlagBuilder.load(FlagBuilder.java:46)
[23:41:34 WARN]:        at in.twizmwaz.cardinal.module.ModuleFactory.build(ModuleFactory.java:208)
[23:41:34 WARN]:        at in.twizmwaz.cardinal.match.Match.registerModules(Match.java:55)
[23:41:34 WARN]:        at in.twizmwaz.cardinal.GameHandler.cycleAndMakeMatch(GameHandler.java:54)
[23:41:34 WARN]:        at in.twizmwaz.cardinal.module.modules.cycleTimer.CycleTimerModule.run(CycleTimerModule.java:57)
[23:41:34 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
[23:41:34 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
[23:41:34 WARN]:        at net.minecraft.server.MinecraftServer.D(MinecraftServer.java:700)
[23:41:34 WARN]:        at net.minecraft.server.DedicatedServer.D(DedicatedServer.java:366)
[23:41:34 WARN]:        at net.minecraft.server.MinecraftServer.C(MinecraftServer.java:649)
[23:41:34 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:555)
[23:41:34 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by TiTo-418** [comment]
```
[00:06:09 WARN]: java.lang.NullPointerException
[00:06:09 WARN]:        at in.twizmwaz.cardinal.module.modules.ctf.FlagBuilder.getFlag(FlagBuilder.java:107)
[00:06:09 WARN]:        at in.twizmwaz.cardinal.module.modules.ctf.FlagBuilder.load(FlagBuilder.java:46)
[00:06:09 WARN]:        at in.twizmwaz.cardinal.module.ModuleFactory.build(ModuleFactory.java:208)
[00:06:09 WARN]:        at in.twizmwaz.cardinal.match.Match.registerModules(Match.java:55)
[00:06:09 WARN]:        at in.twizmwaz.cardinal.GameHandler.cycleAndMakeMatch(GameHandler.java:54)
[00:06:09 WARN]:        at in.twizmwaz.cardinal.module.modules.cycleTimer.CycleTimerModule.run(CycleTimerModule.java:57)
[00:06:09 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
[00:06:09 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
[00:06:09 WARN]:        at net.minecraft.server.MinecraftServer.D(MinecraftServer.java:700)
[00:06:09 WARN]:        at net.minecraft.server.DedicatedServer.D(DedicatedServer.java:366)
[00:06:09 WARN]:        at net.minecraft.server.MinecraftServer.C(MinecraftServer.java:649)
[00:06:09 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:555)
[00:06:09 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by Pablete1234** [comment]
Ctf needs final testing, i added sounds, the last particles missing, and everything should be good to go

Get ctf tested on all the maps you can

**Comment by Pablete1234** [comment]
merged

**Pull request closed without merging**
