### PR TITLE
Implement update notifications

### PR DESCRIPTION
**Pull request by CaptainElliott**
By editing the version in the `update` file it will send a notification that there is a new version available

### CODE REVIEW

**Comment by twizmwazin** [comment]
I think this feature should be implemented using git commit hashes. I'm not sure if either Jenkins or GitHub has an api to hook into.

**Comment by SungMatt** [comment]
@twizmwazin Sending a GET request to `https://api.github.com/repos/twizmwazin/CardinalPGM/git/refs/head/master` will return with the URL of the most recent commit (Under object). The returned URL should look like `https://api.github.com/repos/twizmwazin/CardinalPGM/git/commits/(SHA of commit)`

Alternatively, under object of the result of the first request, it returns SHA of the commit.

**Comment by CaptainElliott** [comment]
I think it is good though that we can send a customized message with the update, stating what it is about or if it is an urgent bug fix

**Comment by CaptainElliott** [comment]
re-writing with new implementation

**Pull request closed without merging**
