### PR TITLE
Added the new way of warns

### PR DESCRIPTION
**Pull request by vYuri**

### CODE REVIEW

**Comment by iEli2tyree011** [comment]
Your build failed.

**Comment by AngelCasillas01** [comment]
@vYuri Try instead of `ChatColorDARK_RED` use `ChatColor.DARK_RED` and  instead of `ChatColor.RED`

**Comment by AngelCasillas01** [comment]
@iEli2tyree011 is that well? (^^)

**Comment by Alfalik** [comment]
Use add instead of added. And, the actual warn message is identic to OCN, I dont see the reason to change it.

**Comment by CaptainElliott** [comment]
The build failed, and what you was trying to do is pointless

**Pull request closed without merging**
