### PR TITLE
Add some more commands (/ml, /maplist, /mt, /myteam)

### PR DESCRIPTION
**Pull request by dentmaged**
All in the title and the code!

### CODE REVIEW

**Comment by dentmaged** [comment]
@CaptainElliott Fixed!

**Comment by iEli2tyree011** [comment]
You have to use `generic.onTeam`. You can't create chat constants and expect them to already be there.

**Comment by AngelCasillas01** [comment]
If this is merged, i'll pull some XML for localization

**Comment by dentmaged** [comment]
@iEli2tyree011 I didn't see that! Sorry!

**Pull request merged**
