### PR TITLE
Fix typo in updating map author names message

### PR DESCRIPTION
**Pull request by CoWinkKeyDinkInc**

### CODE REVIEW

**Comment by Pablete1234** [comment]
Message should be completly removed IMO, it's useless now (imo)

**Comment by twizmwazin** [comment]
How is it useless?

**Comment by Pablete1234** [comment]
@twizmwazin that was a message i added for testing purposes, it isn't really needed

**Comment by Pablete1234** [comment]
i'm going o close this as #1058 refactored alot of that code, and fixed that already

**Pull request closed without merging**
