### PR TITLE
Revise translations

### PR DESCRIPTION
**Pull request by Alfalik**

### CODE REVIEW

**Comment by twizmwazin** [comment]
Are these updates sourced from translate.oc.tc?

**Comment by Alfalik** [comment]
Some was copied from translate.oc.tc, and a few translated/corrected by me.

**Comment by SungMatt** [comment]
I know that @SuHoney can check the Korean version

**Comment by SuHoney** [comment]
Yes, everything seems good :)

**Comment by Alfalik** [comment]
I'll get all translate sourced from OCN's crowdin.

**Pull request closed without merging**
