### PR TITLE
Add Rage Module and start work on blitz

### PR DESCRIPTION
**Pull request by CaptainElliott**
Rage works fine.

Started work on blitz - the fundamentals and logic works, the messages need to be tided up and the scoreboard needs to be implemented as well as the win condition.

### CODE REVIEW

**Comment by iEli2tyree011** [comment]
We'd planned to make the life counter using LazyMetadataValues, do you think you could switch it to that?

**Comment by iEli2tyree011** [comment]
If you need a reference, the KillStreak module uses them.

**Comment by CaptainElliott** [comment]
Working on it as well as completing the blitz module

**Comment by twizmwazin** [comment]
The map system works fine for blitz, it wasn't how I would have done it but if it works fine I don't see a reason why it is "wrong."

**Comment by CaptainElliott** [comment]
How is it redundant? @twizmwazin

**Comment by CaptainElliott** [comment]
I have already re-written it with the LazyyMetaData, I was unaware of it before, I prefer it to the hasmap

**Comment by iEli2tyree011** [comment]
getChild returns any elements that have the name specified. Just check if != null.

**Comment by CaptainElliott** [comment]
I did that before but It would not find the rage tag

**Comment by iEli2tyree011** [comment]
Or, sorry, getChildren does that. getChild just returns the first element I believe.

**Comment by iEli2tyree011** [comment]
How about get children("rage").size() > 0?

**Comment by twizmwazin** [comment]
@CaptainElliott The redundant line was getting an element (or null) named "rage," and then if it was named rage do

@iEli2tyree011 Either getChildren("rage") in a for, or if getChildren("rage").size > 0 would be possibly safer, duplicate modules here shouldn't be an issue though.

**Comment by CaptainElliott** [comment]
Ready to merge the TODOs still need to be done

**Pull request merged**
