### PR TITLE
Add Tito_418 to Developer Team

### PR DESCRIPTION
**Pull request by Zenzoh**
Add Tito_418 to Developer Team

### CODE REVIEW

**Comment by TiTo-418** [comment]
+1 PlZ MERgE thIs

**Comment by twizmwazin** [comment]
nah

**Comment by TiTo-418** [comment]
wHy ????11oneon???1

**Comment by Zenzoh** [comment]
iu antes molabas twiz, nou I jeit yu

**Comment by TiTo-418** [comment]
EPGM IS BETTER N00B B0SS B4R PLZ

**Comment by Alfalik** [comment]
Can we freaking stop the spam?

**Pull request closed without merging**
