### PR TITLE
Add GuiKeepModule, Fix #738

### LINKED ISSUE #738: When crafting tables are broken GUI is closed for everyone
in ocn, if you have a crafting table opened and someone else brakes it, you still have the GUI opened

### PR DESCRIPTION
**Pull request by maestro34**
Players are now able to craft their items even if the workbench is broken.

### CODE REVIEW

**Comment by twizmwazin** [comment]
This doesn't take into account shift-clicking.

**Comment by maestro34** [comment]
Yeah, I'll fix that.

**Comment by Pablete1234** [comment]
tested and works fine

**Comment by twizmwazin** [comment]
Any chance you could sqaush these into a single commit?

**Comment by maestro34** [comment]
Done ;)

**Comment by maestro34** [comment]
I've tested in Minecraft Vanilla and while you are sneaking but you haven't anything in your hand you can still access to the crafting table.
If I don't do that players can access to the workbench but If someone break it, the GUI disappear.

**Comment by CaptainElliott** [comment]
That still does not explain why you are checking that, when I read it is says that, if a player is not sneaking and has nothing in their hand, open the inventory. Have you checked your code?

**Comment by maestro34** [comment]
That's not "and", that's "or".
If the player is sneaking > Nothing in his hand ? Open the inventory.
If not > Always open the inventory.

**Comment by CaptainElliott** [comment]
I meant to say or. But that does not do that you are saying:
if player is not crouching > open inventory
if player has nothing in hand > open inventory

if player is sneaking > don't open
if player has item in hand > don't open

**Comment by iEli2tyree011** [comment]
@CaptainElliott He's saying that you always open the crafting table when not sneaking, and when you have nothing in your hand, you open it regardless. His logic in the code is correct because he's saying open the inventory if the player is not sneaking, or if the player has nothing in their hand.

**Comment by CaptainElliott** [comment]
@iEli2tyree011 ohh I didn't realize that opening a inventory with an empty hand while shifting still opened the inventory

**Comment by iEli2tyree011** [comment]
This seems good to merge, any problems with it? @twizmwazin

**Comment by ryanw-se** [comment]
This is awesome, great work @maestro34!

**Comment by maestro34** [comment]
Thank you, @ryanw-se !

**Comment by twizmwazin** [comment]
thanks, merged

**Pull request closed without merging**
