### PR TITLE
1.9 rebase

### LINKED ISSUE #692: Maps can't be in sub-folders of the repository
if you have as a repository:
/maps

all maps MUST be:
/maps/whatevermap

i think you should be able to do:
/maps/ctw/whatevermap

just how oc.tc repository is made (maps.oc.tc)

### LINKED ISSUE #694: Add advanced repository management
i used a resident for 2 weeks, and by running /newmaps, the pgm rescans it repo for changes. i would like to see this implemented in cardinal since i use cardinal a lot for making and testing maps.

### LINKED ISSUE #823: Reload configuration command
Ability to reload configuration CardinalPGM (config.yml + ranks.xml) without restarting the server.

### PR DESCRIPTION
**Pull request by Pablete1234**
Changes / fixes:
 - Re-done all bossbar system to use the bukkit api.
 - Multitrade now has it's own api in sportbukkit `player.openMerchantCopy(Villager)`
 - Map loading is now recursive! fixes #692
 - Added /cardinal -r to reload config and ranks, fixes #823
 - Added /newmaps to reload the repo, fixes #694 
 - Bossbar time in (DATAbasin) #907 #908
 - Name tags w/ invisiblity #959
 - Time limit bossbar and Tab time delay #916
 - Player dealing 4 hears of damage #871
 - Attributes were changed to work with any name (instead of the enum cardinal had hard-coded in 1.8) and they use the XML attribute child tag instead of an attribute attribute
 - Fixed kit walk-speed (boom box / ender blast), because ranks had inheritance, one rank gave the speed, and the inherited one set it to the default again
 - Fix observers' hits counting to the death tracker #688
 - Permissions are given to the player even if they already have them #809

### CODE REVIEW

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/issues/959
https://github.com/twizmwazin/CardinalPGM/issues/916
https://github.com/twizmwazin/CardinalPGM/issues/871

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/issues/694
https://github.com/twizmwazin/CardinalPGM/issues/692

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/issues/823

**Comment by SungMatt** [comment]
Does map loading have options for excluded folders?

**Comment by TiTo-418** [comment]
@SungMatt Just don't put them into \maps

**Comment by Pablete1234** [comment]
@SungMatt the recursive map loading wasn't done a while back because of that asked config, i really think it's not eorth delaying the change for a config, don't put them inside /maps and they won't be included

**Comment by ryanwse** [comment]
That boss bar code still makes me cringe to this day, glad to see it getting replaced.

**Comment by Pablete1234** [comment]
@ryanwse Yeah, the bukkit api simplifies stuff alot, but still, it doesn't allow a custom title for each player, so i had to make my own :P

**Comment by RickAstIey** [comment]
Vouch really good defender

**Comment by SungMatt** [comment]
@Pablete1234 That's cleaning up the `maps` folder by moving the mess to the `.` folder, something I believe none of us intended to do. But of course, more organisation in a small folder helps too!

On a side note, do you think that adding these fixes in separate PRs will be more future-ready as we build further on Cardinal?

**Comment by Pablete1234** [comment]
@SungMatt Well, i like the idea that 1.9 brings all therse new features, for bigger changes (like what i'm doing to kits) i already have a separate pr, and also, now that it's all in one commit, i don't feel like starting to copy-paste parts of code into other commits and removing it from the main 1.9 commit

**Comment by TiTo-418** [comment]
https://github.com/twizmwazin/CardinalPGM/issues/745

**Comment by Pablete1234** [comment]
Currently doesn't build because sportBukkit changed Team.setCollisionRules to Team.setOption...., but it's fixed in #988 along with the title respawn module

**Comment by Pablete1234** [comment]
merged

**Comment by SungMatt** [comment]
Onwards, and upwards!

**Pull request closed without merging**
