### PR TITLE
Update max-build-height msg

### PR DESCRIPTION
**Pull request by Pablete1234**

### CODE REVIEW

**Comment by dentmaged** [comment]
@Pablete1234 Use `git commit --amend -m "Update max-build-height msg"` to change your change your commit.

**Comment by Pablete1234** [comment]
does that change or replace a commit?

**Comment by dentmaged** [comment]
@Pablete1234 It edit's a commit it's just like doing a normal commit.

**Comment by Alfalik** [comment]
You forgot to change line 72.

**Comment by Pablete1234** [comment]
i made this commit like 3 times already ..., going for the 4th time

**Comment by twizmwazin** [comment]
@Pablete1234 Use dentmaged's suggestion rather than making a new commit and a new PR.

**Comment by Pablete1234** [comment]
i'm on it

**Comment by Pablete1234** [comment]
ok, i definetly do not know what i did, i tried to do what det said, and it sent this http://gyazo.com/d60e68d379122bb65050c0531cf908ec , so i git pull, and suddently i realize i just merged the same branch into itself...

**Comment by dentmaged** [comment]
@Pablete1234 Force push it (```git push -f```)

**Comment by Pablete1234** [comment]
could have told it b4, how can I rollback?

**Comment by Pablete1234** [comment]
Yay \ö/, i resetted the last commit, and pushed it without the last commit amending it to the main one

**Comment by twizmwazin** [comment]
merged

**Pull request closed without merging**
