### PR TITLE
Prevent observers opening other observers inventories, fixes #691

### LINKED ISSUE #691: observers can open other observer's inventories
observers can open other observer's inventories

### PR DESCRIPTION
**Pull request by ryanw-se**

### CODE REVIEW

**Comment by iEli2tyree011** [comment]
Thanks!

**Comment by ryanw-se** [comment]
@iEli2tyree011 Why did you manually commit this rather than just merging the PR?

**Comment by CaptainElliott** [comment]
He didn't manually commit ithttps://github.com/twizmwazin/CardinalPGM/commit/f454a6c8b62cc06013b0707e5418c550fb8d5c1d

**Comment by ryanw-se** [comment]
@CaptainElliott ```iEli2tyree011 committed 5 days ago```, if this was merged I would have received an email and this PR would have turned purple, not red. Thus, I never knew this got accepted because instead of merging it, he manually pushed my commit.

**Pull request closed without merging**
