### PR TITLE
Update es.xml

### PR DESCRIPTION
**Pull request by ItzWid13**

### CODE REVIEW

**Comment by dentmaged** [comment]
Please add more detail to the title next time

**Comment by TiTo-418** [comment]
@dentmaged no needed
+1 to the translate

**Comment by ElFlambMC** [comment]
+1

**Comment by Rafitamolin** [comment]
+1

**Comment by Alfalik** [comment]
Should be "se puede". The message is in present, not in past. Is totally weird write like you did in the  commit.

**Comment by TiTo-418** [comment]
@Alfalik true, close this

**Comment by Alfalik** [comment]
Already fixed in 7ec6f4e

**Pull request closed without merging**
