### PR TITLE
Add configuration option to kill mobs on map load

### PR DESCRIPTION
**Pull request by dentmaged**
When editing maps sometimes mob spawn. I think this would be a useful feature for those who don't use MCEdit, however I don't think that this is a requirement. I will understand if you don't want to merge it.

### CODE REVIEW

**Comment by AngelCasillas01** [comment]
Try to add this but for kill mobs within 2 blocks because some maps like Cake Wars there is spiders

**Comment by dentmaged** [comment]
@AngelCasillas01 What do you mean by "kill mobs within 2 blocks"? 2 blocks within what? a region?

**Comment by CoWinkKeyDinkInc** [comment]
@dentmaged Paintings, itemframes, and the player are also entities that you'd may want to keep in a map.

**Comment by dentmaged** [comment]
@CoWinkKeyDinkInc Of course! Thanks @twizmwazin and @CoWinkKeyDinkInc!

**Comment by CaptainElliott** [comment]
This is a map issue, not a plugin issue. Maps may want to have things spawned in them inside the world files, it is something we should not allow users to disable.

**Comment by dentmaged** [comment]
@CaptainElliott Okay! It's disabled by default. Maybe something in the XML, although it wouldn't work on Overcast, it would be good to test maps with.

**Comment by CaptainElliott** [comment]
Overcast has a mobs filter

**Pull request closed without merging**
