### PR TITLE
Add purple dux star to all contributors

### PR DESCRIPTION
**Pull request by Alfalik**
We'll (contributors) be happy to have this PR merged. Isn't really useful and doesn't have permissions, but is a way to thank all players that help and spent time finding/catching all errors and issues in Cardinal.
Here it's how it looks: http://gyazo.com/8a4ce4c6835b95d92ec2c8dd23516cde

Edit: can't find IGN of @Rafitamolin

### CODE REVIEW

**Comment by Rafitamolin** [comment]
My IGN is Compulsivo.

**Comment by iEli2tyree011** [comment]
@twizmwazin and I already decided that we don't want to add this.

**Comment by TiTo-418** [comment]
@Alfalik +1, gracias por hacer esta PR aunque no sea aniadida, sinceramente me hubiera gustado mucho que la pusieran.

**Comment by Alfalik** [comment]
@TiTo-418 I don't really know why this has been added. We aren't required to help developing the plugin and anyway, we do it. Besides, if they have a selfish mentality, isn't our problem.

**Comment by CaptainElliott** [comment]
as @iEli2tyree011 said this is something that will not be implemented, besides people can see the contributors list

**Pull request closed without merging**
