### PR TITLE
Update the scoreboard.

### PR DESCRIPTION
**Pull request by Zenzoh**

### CODE REVIEW

**Comment by Alfalik** [comment]
You mean "Objectives", not "Objetives"

**Comment by dentmaged** [comment]
I don't see why this PR is necessary. Would you mind explaining it?

**Comment by ElFlambMC** [comment]
@dentmaged could you add me on skype to talk.

**Comment by Zenzoh** [comment]
@dentmaged In OCN it is now well.

**Comment by iEli2tyree011** [comment]
Why did you only change one of them, and also making it less descriptive?

**Comment by dentmaged** [comment]
There should also be only one commit.

**Comment by Zenzoh** [comment]
In overcast network has only been updated CTW

**Comment by Alfalik** [comment]
@Zenzoh Why don't you wait until all servers update to 1.8? Then make one PR with all the changes

**Comment by twizmwazin** [comment]
This is useless

**Pull request closed without merging**
