### PR TITLE
Fix kit health, food and saturation

### PR DESCRIPTION
**Pull request by Pablete1234**
Health : 1-20
Food: 0-20
Health is no longer the max health, it's the player health
Health, food and saturation don't get added, they get set if they are bigger than the actual player's health/food/saturation, unless forced
Taken from: https://docs.oc.tc/modules/kits

Test video: http://youtu.be/caXbso5aOAQ
Xml Used : http://pastebin.com/zmYHrXPr
The slot of the sword tells what region i'm in

### CODE REVIEW

**Comment by SungMatt** [comment]
Won't this break maps like Dust where there are only 2 hearts displayed rather than 10 hearts?

**Comment by Pablete1234** [comment]
@SungMatt maps don't use the health tag to lower the max health, they use negative health boost

**Comment by twizmwazin** [comment]
can someone get results with dust?

**Comment by Pablete1234** [comment]
@twizmwazin i have a map that uses same effect as dust and works as expected

**Comment by twizmwazin** [comment]
So do we think this is good to merge? @iEli2tyree011

**Comment by Pablete1234** [comment]
@iEli2tyree011 fell out of the world

**Comment by twizmwazin** [comment]
merged

**Pull request closed without merging**
