### PR TITLE
Change message in /wl toggle

### PR DESCRIPTION
**Pull request by TiTo-418**

### CODE REVIEW

**Comment by TiTo-418** [comment]
@iEli2tyree011 @twizmwazin

**Comment by iEli2tyree011** [comment]
What's the point of changing this? Also, please don't tag us in issues/pull requests for no reason. We will get around to them eventually, regardless.

**Comment by TiTo-418** [comment]
"In the future, you don't need to close pull requests. Feel free to ping me or Elly on a pull request if we haven't commented after a few days."
If you put '/wl on' appear 'WhiteList Enabled' but if you put '/wl toggle' appear 'WhiteList On'

**Comment by iEli2tyree011** [comment]
Can you change the commit message? "Update WhitelistCommands.java" is very vague and is the default message when using the Github editor.

**Comment by TiTo-418** [comment]
Oh, the commit message...

**Comment by iEli2tyree011** [comment]
I'd be happy to merge it if you change the message. I didn't realize there was an inconsistency. :grinning:

**Pull request closed without merging**
