### PR TITLE
Make HTML statistics page

### PR DESCRIPTION
**Pull request by CaptainElliott**
currently only uploads to pastehtml

### CODE REVIEW

**Comment by SuHoney** [comment]
That looks cool :+1:

**Comment by CaptainElliott** [comment]
example http://captainelliott.github.io/tests/cardinalstatistics

**Comment by SuHoney** [comment]
:+1:

**Comment by ryanw-ny** [comment]
@CaptainElliott The flairs show up as ? on your transcript. Might want to fix that

**Comment by CaptainElliott** [comment]
@ryanw-ny I planned to do that later and other cosmetic things. I plan on making the teams use colours and perhaps use players avatars

**Comment by ryanw-ny** [comment]
@CaptainElliott rad!

**Comment by CaptainElliott** [comment]
@ryanw-ny rad?

**Comment by ryanw-ny** [comment]
@CaptainElliott ... its a really lame slang word that means "It means great, terrific, wonderful."

**Comment by AngelCasillas01** [comment]
Cool

**Comment by AngelCasillas01** [comment]
Do you wil create a page for 1 match or just will work like in Overcast?

**Comment by twizmwazin** [comment]
Commit merged manually

**Pull request closed without merging**
