### PR TITLE
Add Chat channels and Fix wool touches 

### PR DESCRIPTION
**Pull request by CaptainElliott**
I know some parts are a bit messy but it all works

### CODE REVIEW

**Comment by twizmwazin** [comment]
Thanks!

**Comment by iEli2tyree011** [comment]
What was the problem with the wool touches? They both worked for me before, it just looks like you switched the two around

**Comment by CaptainElliott** [comment]
They would not work if you picked it off the ground, there was also two identical `onWoolPickup` methods

**Comment by iEli2tyree011** [comment]
Why wouldn't they work? I'm not sure what the point of switching them around was, but it doesn't affect anything I suppose

**Comment by CaptainElliott** [comment]
Nothing was switched around, there was two events of `InventoryClickEvent`.

`InventoryClickEvent` does not register when a player picks up the wool from item form so I added `PlayerPickupItemEvent` the diff looks weird though

**Pull request merged**
