### PR TITLE
Update inventory viewer

### PR DESCRIPTION
**Pull request by Pablete1234**
Changes:
  - fixes inventory not updating when drag-clicking items
  - fixes inventory flickering (#716)
  - uses DisplayName instead of team color + Name (ranks also show)
  - if a player switches teams, the inventory keeps updating with the new items & new name

Missing:
  - localization
  - remove debug stuff

### CODE REVIEW

**Comment by twizmwazin** [comment]
It would make sense to close the view when the player joins obs, but its up to you if you'd like to write it.

**Comment by Pablete1234** [comment]
@twizmwazin it's not about writting it, it's that maybe someone does /join obs, and then joins the other team, instead of just typing /join (the other team), and this way the inventory would still be opened, but maybe i'll make it close itself

**Comment by Alfalik** [comment]
I've seen an ```/inventory <player>``` or ```/inv <player>``` command on the development logs of Overcast. You should probably add it

**Comment by Pablete1234** [comment]
I'm getting a ConcurrentModificationException line 365
```
364            List<UUID> viewers = viewing.get(uuid);
365            for (UUID vieweruuid : viewers) {
366                if (Bukkit.getPlayer(vieweruuid) != null) {
367                    Bukkit.getPlayer(vieweruuid).closeInventory();
368                }
369            }
```
How can it be concurrent modification if i just created a local variable, and the one i'm doing the for at is the local one

**Comment by dentmaged** [comment]
@Pablete1234 try using an iterator. Im not very good with CMEs.

**Comment by TiTo-418** [comment]
Works perfect

**Comment by Pablete1234** [comment]
This needs testing with more than 2 players (1 joined +2 opening his inv), test kicking the joined player, one of the observers, and see if you get any errors on console
I will add localization when i think there are no errors

**Comment by Pablete1234** [comment]
If someone could test this it would be nice, I added localization, and changed some stuff

**Comment by Pablete1234** [comment]
@twizmwazin i think this is ready to merge (as soon as some testing is done)
any1 willing to test this?

**Comment by twizmwazin** [comment]
merged

**Pull request closed without merging**
