### PR TITLE
Add auto potion bottle remover

### PR DESCRIPTION
**Pull request by ShinyDialga45**

### CODE REVIEW

**Comment by ShinyDialga45** [comment]
Thanks, focused too much on making the module itself good :P

**Comment by iEli2tyree011** [comment]
Can you make this into one commit please?

**Comment by iEli2tyree011** [comment]
Also, I'd recommend storing the slot value as a `final int` and then referring to it in the runnable, as the player may have switched items that they are holding.

**Comment by iEli2tyree011** [comment]
Looks good. Thanks!

**Pull request merged**
