### PR TITLE
Use max instead of maxOverfill when a player is joining a team

### PR DESCRIPTION
**Pull request by Pablete1234**
hopefully solves #553

### CODE REVIEW

**Comment by twizmwazin** [comment]
I'm pretty sure 1.2x is how Overcast handles it

**Comment by Pablete1234** [comment]
@twizmwazin then we should change it so that players can't bypass the regular join limit, and if we are not going to use the maxOverfill, it may be kinda useless to have, maybe an op-only perm?

**Comment by Pablete1234** [comment]
@twizmwazin  I changed it, but now it makes no sense to keep the maxOverfill anymore, this is a scrimm plugin, and I don't think we need permissions for maxOverfill, the regular max should be used

Also, about the 1.2x, I think that is how it works for public matches, but in tournaments (or any tm server) they dont do that because if you look at any HoC xml, they have "max=10" and no max overfill, but still when playing scrimms op's couldn't join to teams with 10 players in (or maybe op doesn't have the permission to join using "maxOverfill")

**Comment by TiTo-418** [comment]
@Pablete1234 +1

**Comment by Pablete1234** [comment]
@twizmwazin updated, max overfill is 25% more than regular max (https://docs.oc.tc/modules/teams)

**Comment by Alfalik** [comment]
The additional 25 percent is for donator purposes. It's highly pointless have a ```max-overfill``` in Cardinal. I'd just set ```max-overfill``` & ```max``` to the same number.

**Comment by Pablete1234** [comment]
the purpose of this PR is to use max instead of max-overfill, I don't know if twiz actually want me to get rid of everything related to max-overfill, or maybe do it a op-only feature?

**Comment by TiTo-418** [comment]
I agree with @Alfalik

**Comment by Pablete1234** [comment]
@TiTo-418 the thing is, why do you want 2 numbers that are the same? just get rid of one of them, i would remove max overfill overall (plugin would just ignore that in the xml)

**Comment by twizmwazin** [comment]
I'm going to merge this with the justification that you can always change the team size. I will consider a permission for specific players to join to the max overfill.

**Pull request closed without merging**
