### PR TITLE
Added a line which specify the usage of SportBukkit 1.8

### PR DESCRIPTION
**Pull request by AngelCasillas01**
I can add this on the wiki if you merge this, or if you want too

### CODE REVIEW

**Comment by twizmwazin** [comment]
You don't need sportbukkit installed separately to compile.

**Comment by AngelCasillas01** [comment]
@twizmwazin  may i add this on the wiki?

**Comment by AngelCasillas01** [comment]
@twizmwazin is this going on Issue Reporting

**Comment by SungMatt** [comment]
Just to let you know, the [Installing CardinalPGM](https://github.com/twizmwazin/CardinalPGM/wiki/Installing-CardinalPGM) page has a part on SportBukkit. As @twizmwazin said, SportBukkit is not necessary for compiling of Cardinal. I do not see the need of having a wiki and a README being a wiki.

**Pull request closed without merging**
