### PR TITLE
Prevent cores' lava to be removed by water buckets

### LINKED ISSUE #720: Cores are still editables
The first clip isn't fixed: https://www.youtube.com/watch?v=Q-F0bEGkprA&feature=youtu.be
For reference: https://github.com/twizmwazin/CardinalPGM/issues/660#issuecomment-104850172

Edit: Also happen with blocks with gravity

### PR DESCRIPTION
**Pull request by Pablete1234**
It prevents buckets to be dumped inside lava (both water buckets and lava buckets)
As it is right now in cardinal, you can't place lava arround the core, and you can place water inside lava,
Additonally, you can place lava in the core region if you are clicking in a block outside of the region, but not against a block that's inside the core
Fixes #720

### CODE REVIEW

**Comment by Pablete1234** [comment]
@twizmwazin opinions?

**Comment by twizmwazin** [comment]
Needs testing

**Comment by Pablete1234** [comment]
I tested it myself and works as expected, try testing it too

**Comment by Pablete1234** [comment]
@twizmwazin Me and @TiTo-418 tested this and it seems like there is a bug, where if you place water ontop of the water(so it flows ontop of the lava) and when it's flowing placing water inside the lava.
Also in OCN it's not about the lava, it's about the blocks that have lava, even if you /fill them out with air, water won't flow inside the lava, it's like a region with a deny-blocks, both placing, removing blocks or water flowing inside:
http://gyazo.com/4f417d02c5d60b27d46f6761d245723f

**Comment by Pablete1234** [comment]
@twizmwazin I changed everything from "region + has lava" to "lava", the lava region can't be edited, even if i remove the lava with world edit, and I prevented water flowing inside the lava too
Just like in OCN:
https://gyazo.com/fb3c5b03b7db2c82676c00e4e802015d

I've done some testing and I could not replace the lava in any way, I think it's ready to merge, anyone else wants to do some testing?

**Comment by Pablete1234** [comment]
@twizmwazin

**Comment by twizmwazin** [comment]
If I could get one tester to confirm that this works I'll merge it. Otherwise I'll get around to testing it tomorrow.

**Comment by TiTo-418** [comment]
@twizmwazin I'll test it, do you want a video?

**Comment by twizmwazin** [comment]
@TiTo-418 sure

**Comment by TiTo-418** [comment]
@twizmwazin I tried but a couldn't upload a video (thanks windows 10) but i did't find a way to remove the lava with buckets.

**Comment by twizmwazin** [comment]
merged

**Pull request closed without merging**
