### PR TITLE
Change the PlayerList title

### PR DESCRIPTION
**Pull request by dentmaged**
This PR expands on #729. All it does is change to use the player's display name in the player list header.

### CODE REVIEW

**Comment by iEli2tyree011** [comment]
If I'm not mistaken, contributors may not have a UUID. You would want to use their name in that case. Also, we may want to consider making the getName method part of a util class as it likely can have many other users.

**Comment by CaptainElliott** [comment]
Yes, a UUID does not have to be defined, however if one is not defined then that name will not get any recognition so they can just be given a cyan name

**Comment by dentmaged** [comment]
@iEli2tyree011 @CaptainElliott Done!

**Comment by dentmaged** [comment]
@iEli2tyree011 @CaptainElliott Done!

**Comment by CaptainElliott** [comment]
@dentmaged neat!

**Comment by Pablete1234** [comment]
going to merge?

**Comment by dentmaged** [comment]
@iEli2tyree011 Done!

**Comment by iEli2tyree011** [comment]
@dentmaged Looks good, thanks!

**Pull request closed without merging**
