### PR TITLE
Add /recycle {time}

### PR DESCRIPTION
**Pull request by javipepe**
It should be working, can't check it right now but everything seems alright. It just sn's the current map when it's about to cycle.

### CODE REVIEW

**Comment by twizmwazin** [comment]
I don't like the idea of reusing the setnext and cycle commands. I'd rather you got the current loaded map and set that as the next map without dispatching the command. Then run the cycle timer.

**Comment by CaptainElliott** [comment]
Its probably inefficient to call a command, best cycle it manually. Also you should there are many NPE's that could occur, such as a player not specifying a team, moreover the /recycle command does not accept any parameters and ends the game with whatever team is currently winning

**Comment by javipepe** [comment]
Oh, I'll play with the <code>cycle()</code> method later and will push it on here

**Comment by twizmwazin** [comment]
It is also worth noting that the build failed, please use a proper IDE such as IntelliJ or Eclipse, and push code using git, not GitHub's editor.

Also, you wouldn't want to `cycle()`, you would want to start the cycle timer.

**Comment by dentmaged** [comment]
@javipepe Also replace line 47 with recycle (the void name), as cycle is used before in the class.

**Comment by AngelCasillas01** [comment]
I think that if you unbroke your code, this can be merged :o

**Comment by twizmwazin** [comment]
@AngelCasillas01 I'm not merging anything that does not build.

**Comment by AngelCasillas01** [comment]
@twizmwazin on your recycle commit what have you used?

**Comment by twizmwazin** [comment]
@AngelCasillas01 I wrote the command myself, this was not merged.

**Comment by AngelCasillas01** [comment]
@twizmwazin Nice job i have tested already!

**Pull request closed without merging**
