### PR TITLE
Fix Punishments messages and added unicodes.

### PR DESCRIPTION
**Pull request by felipufeliu**

### CODE REVIEW

**Comment by iEli2tyree011** [comment]
Felipe, your Travis builds are failing. We can't accept code that is broken, can you check over what might be causing the error?

**Comment by Superjd10** [comment]
I don't know anything about Java or how Travis works, but looking in the errors, the Travis build failed because he is calling "PermissionModule" in the mentioned lines (84, 87... you can check which lines in "Details" right under my comment)

You didn't import PermissionModule: 

```java
import in.twizmwaz.cardinal.module.modules.permissions.PermissionModule;
```

**Comment by felipufeliu** [comment]
@iEli2tyree011 lol, when I tested it on IntelliJ it worked, I think I copy it wrong or something, I'll check it

**Comment by AngelCasillas01** [comment]
@felipufeliu this will not mpbe merged?

**Comment by CaptainElliott** [comment]
It was merged here instead
https://github.com/twizmwazin/CardinalPGM/commit/598eee1cba8b009de5526b39dff8eadbc4df0086

**Comment by Superjd10** [comment]
Damm @CaptainElliott ninja :(

**Comment by AngelCasillas01** [comment]
@CaptainElliott bt when i kick dosen't appears like OCN does, he only fix Warn mesages

**Comment by CaptainElliott** [comment]
Could You show a screenshot of how it appears?

**Comment by AngelCasillas01** [comment]
@CaptainElliott  okk

**Comment by felipufeliu** [comment]
@CaptainElliott I know it was fixed on that pr but only the Admin Chat Message, this one have more fixes.

**Comment by felipufeliu** [comment]
@CaptainElliott 
http://prntscr.com/69icmh
http://gyazo.com/e2d9b7534dbd6e2456dbd691a36844bb
http://gyazo.com/c13aa7292748a8a2165840857f3159ee

**Comment by CaptainElliott** [comment]
@felipufeliu could you then rebase and make a new PR that does not have any errors?

**Comment by felipufeliu** [comment]
@CaptainElliott This one already works http://gyazo.com/d6ea6826f62e13fc380b897ac68a703c

**Comment by twizmwazin** [comment]
@felipufeliu I think he is asking for a single commit pull request. This pr isn't going to be merged.

**Comment by AngelCasillas01** [comment]
@CaptainElliott http://prntscr.com/6f6qgb Look, this dosen't look so well :P

**Comment by CaptainElliott** [comment]
@AngelCasillas01 https://github.com/twizmwazin/CardinalPGM/commit/25834b661669844b42910f79479fa61be057b2a0

**Comment by AngelCasillas01** [comment]
@CaptainElliott Compiling!

**Pull request closed without merging**
