### PR TITLE
Adding team in "Motd"

### PR DESCRIPTION
**Pull request by Prodigy4532**
http://gyazo.com/c767311f6d3bc7af9ee94f5ee05cdf13

### CODE REVIEW

**Comment by twizmwazin** [comment]
I'm not sure if I like this. @iEli2tyree011 

But regardless, the commits will need to be squashed, seriously guys, don't use the github editor, ever. I don't like the big CardinalPGM branding, that would have to go, and I'm not sure why there is a ton of leading whitespace, you won't be able to center the text, so left-aligned looks better.

**Comment by Prodigy4532** [comment]
i use NetBeans for this.

**Comment by twizmwazin** [comment]
@Prodigy4532 But you didn't commit & push using git, you copyed and pasted with the GitHub editor. Regardless, read above

**Comment by Pablete1234** [comment]
it would be nice if you could totally customize it, like:
motd: Team ; playing - {1} - Cardinal

**Comment by Prodigy4532** [comment]
nice idea

**Comment by twizmwazin** [comment]
Closing in favor of #756

**Pull request closed without merging**
