### PR TITLE
Support teams being optional

### PR DESCRIPTION
**Pull request by twizmwazin**
This pull request is here to ask others to test this branch, and find any bugs or inconsistencies before this I merge this into master. If you know what you are doing please feel free to do everything you can to try and break this, and report back the issues.

### CODE REVIEW

**Comment by Pablete1234** [comment]
What's the purpose of "optional teams" what does that mean?

**Comment by dentmaged** [comment]
@Pablete1234 What if the match is FFA? That's what Elly said to me when I asked about it.

**Comment by Pablete1234** [comment]
i se FFA as 1 team with friendly fire on

**Comment by twizmwazin** [comment]
@Pablete1234 That wouldn't support per-player scoring

**Comment by Pablete1234** [comment]
@twizmwazin That makes sense

**Comment by Eudaldca** [comment]
I found an issue, if you try to /end a regular match (Tested on boom TE) it gives out an error. [Log](http://pastebin.com/pRgxMh66/)
Also, if you try to cycle to an FFA match, it fails to cycle, [the xml](https://oc.tc/forums/topics/556b42175f35b90fe200689b/) is valid. I don't know if it is supposed to be able to cycle already, but I posted it just in case.

**Comment by twizmwazin** [comment]
@Eudaldca Thanks, fixed

**Pull request merged**
