### PR TITLE
Prevent observers blowing up objectives

### LINKED ISSUE #677: Observers can damage objectives if they ignited TNT on a participating team whilst the game is running and they switch to Observers before it explodes
Video: http://youtu.be/5BC3SA-mu_k

Title by @dentmaged

### PR DESCRIPTION
**Pull request by Pablete1234**
fixes #677

### CODE REVIEW

**Comment by twizmwazin** [comment]
This doesn't consider players not on a team

**Comment by Pablete1234** [comment]
@twizmwazin fixed (I think)

**Comment by Pablete1234** [comment]
@twizmwazin Anything else that needs to be added?

**Comment by twizmwazin** [comment]
merged

**Pull request closed without merging**
