### PR TITLE
Added <deathMsg> On es.xml

### PR DESCRIPTION
**Pull request by AngelCasillas01**

### CODE REVIEW

**Comment by CaptainElliott** [comment]
Feedback? @TiTi-418  @Superjd10

**Comment by Superjd10** [comment]
Many spelling mistakes:

The "ó" in:
-explotó
-murió
-calló (instead of the correct "cayó"
-explosión
-tiró
-sofocó

Missing space in "{0} fue {1} tirado desde un lugar alto ({2})por la TNT de {3}"

"spleefed" 

"respiriar" instead of "respirar", 


So no, this shouldn't be merged.

**Comment by AngelCasillas01** [comment]
@Superjd10  Can be corrected

**Comment by AngelCasillas01** [comment]
@Superjd10 And how respirIar, the correct way is respirar

**Comment by AngelCasillas01** [comment]
@CaptainElliott There ya go

**Comment by Superjd10** [comment]
"tiradó" isn't a word, you still forgot some "ó" (e.g. "olvidó")

**Comment by AngelCasillas01** [comment]
@Superjd10  Apple keyboard dosen't detect that issue

**Comment by Superjd10** [comment]
@AngelCasillas01 Sorry, I lost you on "Apple keyboard" :cry:

**Comment by AngelCasillas01** [comment]
@Superjd10 iOS has an auto-corrector that dosen't detect what youiru are saying, the ó things it's true but other things nope

**Comment by TiTi-418** [comment]
<fallPlayerKnocked>{0} fue {1} tiradó desde un lugar alto ({2}) por {3} {4}<b>E</b></fallPlayerKnocked>
Esta E no deberia estar ahi

**Comment by AngelCasillas01** [comment]
tomorrow i'll fix it

**Pull request closed without merging**
