### PR TITLE
Update es.xml

### PR DESCRIPTION
**Pull request by Eudaldca**
Updated with *all* the localisations existing up to date. Everything commented in #572 is fixed.

### CODE REVIEW

**Comment by AngelCasillas01** [comment]
`<drowning>{0} se ha olvidado de respirar</drowning>`?
Are you using Google Translate for this? Because should be "se le ha olvidado respirar" and when i use the en.xml translate appears the same that what you just put, idk but it is just a opinion

**Comment by AngelCasillas01** [comment]
image

Proof

**Comment by felipufeliu** [comment]
@angelCasillas01 I don't think it's necesary to upload "proof" since this isn't a report.
Also I think that how Eudaldca do it's okay.

**Comment by Alfalik** [comment]
Already check all the changes, it seems okay and correctly translated.

**Comment by AngelCasillas01** [comment]
@felipufeliu make sense that you spell se ha olvidado de respirar, all is well expeting that for me, the good way for me is " Se le ha olvidado respirar"

**Comment by Superjd10** [comment]
Both aren't the best, a better option would be: {0} ha olvidado respirar.

**Comment by TiTi-418** [comment]
@iEli2tyree011 Hey! You can merge this, i will do a PR later fixing this error

**Comment by AngelCasillas01** [comment]
@TiTi-418 hasla tu pero con las cosas :p :p

**Comment by TiTi-418** [comment]
@AngelCasillas01 Es mas facil que mergeen esto y que solo corriga una cosa :P

**Comment by Superjd10** [comment]
@TiTi-418 El resultado es el mismo. // The result is the same.

**Comment by TiTi-418** [comment]
This can be closed with this PR https://github.com/twizmwazin/CardinalPGM/pull/599

**Pull request merged**
