### PR TITLE
Changes to improve consistency and coding conventions

### PR DESCRIPTION
**Pull request by iEli2tyree011**

### CODE REVIEW

**Comment by iEli2tyree011** [comment]
We're going to use a system with permissions to manage toggles. Also, you had it so that if I did /a, everyone would talk in admin chat, /g for everyone talking in global. We're saving all the player-specific settings until the implementation of permission management at a future date.

**Comment by twizmwazin** [comment]
There will be a localization system soon

**Comment by CaptainElliott** [comment]
It was set up so team chat was default so whenever you talked normally you would talk in team chat. If you did `/a msg` then it would end an admin message, but speaking normally would still be in team chat, unless you switched it with just `/a`

**Comment by iEli2tyree011** [comment]
Yes, but when I did /a, it would set *everyone's* default channel to admin chat.

**Comment by CaptainElliott** [comment]
ohhh yeah, I see

**Pull request merged**
