### PR TITLE
Added in sounds upon recieving a private message

### LINKED ISSUE #913: Private messages sounds are not implemented yet.

### PR DESCRIPTION
**Pull request by SungMatt**
Fixes #913, "Private messages sounds are not implemented yet.".

Do let me know if there is anything missing or I've messed up somewhere in git.

### CODE REVIEW

**Comment by SungMatt** [comment]
I've tested this with two accounts on the server, running both /tell and its variants and /r and its variants and it is working. If a more rigorous testing method is required (other than dropping something on my machine) please let me know.

**Comment by Pablete1234** [comment]
@SungMatt you also need to add the option (/toggle pms or PrivateMessageSounds), look for the exact name on ocn

**Comment by Eudaldca** [comment]
@SungMatt @Pablete1234 Now /toggle pms stands for private message sounds, and /toggle privatemessages's alias is now pmr.

**Comment by SungMatt** [comment]
@Pablete1234 Thanks.

@Eudaldca This doesn't affect this PR, but noted.

**Comment by Eudaldca** [comment]
@SungMatt It was changed, /toggle privatemessages was pms before.

**Comment by SungMatt** [comment]
@Eudaldca Will fix separately, thanks!

**Comment by SungMatt** [comment]
I'll try to finish this PR by tonight/next morning, before I go for my cruise.

**Comment by SungMatt** [comment]
Should be good to go now.

**Comment by Pablete1234** [comment]
@SungMatt didn't test, but seems good to me looking at the code, anyone tested?

**Comment by Pablete1234** [comment]
@SungMatt i tested this and when doing /toggle pms it toggled private messages, not private message sounds

**Comment by SungMatt** [comment]
@Pablete1234 This happened to me earlier, it did not appear when the server was started from scratch. Check the config file, it probably wasn't updated, as I believe the server does not try to write the config file over to prevent the loss of data.

Do tell me if you encounter the same if you start from just the server jar and the plugin.

**Comment by SungMatt** [comment]
As for this PR, I'll look into splitting the config file into a config database and a server-only config file that can be updated without deleting user info.

**Comment by Pablete1234** [comment]
@SungMatt @twizmwazin should we merge this and make another pr to create the "new config" system?

**Comment by twizmwazin** [comment]
No, finish implementing the feature fully before merging

**Comment by Pablete1234** [comment]
@twizmwazin but they are different features, private message sounds are fully working. He is talking about about adding a new config system all arround, maybe that should be a different feature all arround

**Comment by twizmwazin** [comment]
Gotcha, merging

**Pull request closed without merging**
