### PR TITLE
Update es.xml

### PR DESCRIPTION
**Pull request by Eudaldca**

### CODE REVIEW

**Comment by TiTi-418** [comment]
disagree with line 123

**Comment by Superjd10** [comment]
I agree with @TiTi-418

**Comment by Eudaldca** [comment]
I have just seen it. I translated from the english string without looking at the text between "<>". In overcast, the max-overfill refers to the amount of premium users that can join when teams are full, so in the english translation of cardinal it should be written tesm size indtead of max-overfill. Feel free to make a new PR with "máxima capacidad", I agree with you. Make it also for en.xml.

**Comment by TiTo-418** [comment]
@Superjd10 Can you make it in en.xml?

**Comment by Superjd10** [comment]
@TiTo-418 what do you mean?

**Pull request closed without merging**
