### PR TITLE
Add ranks system

### PR DESCRIPTION
**Pull request by iEli2tyree011**
Adds a rank system to Cardinal. Still working on finishing touches and adjustments.

### CODE REVIEW

**Comment by TiTo-418** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES :DDDDDDDDDDDDD

**Comment by Alfalik** [comment]
From testing:

+ Permissions nodes aren't working for me, could you confirm?
+ Do you plan on adding inheritance?
+ A default rank should be added with default permissions, like ```
<permission>cardinal.chat.global</permission>```

**Comment by Pablete1234** [comment]
yay \ö/

**Comment by TiTo-418** [comment]
Cool :D
<a href="http://imgur.com/861X3wx"></a>

**Comment by iEli2tyree011** [comment]
@Alfalik Permissions are working for me, and inheritance is planned to be added. A default rank will be added as well.

**Comment by TiTo-418** [comment]
I think a /ranks list is needed :P

**Comment by TiTo-418** [comment]
I can not start with this xml: http://pastebin.com/psJH2juY
I dont know if it has errors :P

**Comment by iEli2tyree011** [comment]
@TiTo-418 What do you mean? Are there errors in the Console, or does it just not list the ranks under /ranks list? I can't fix a problem if I don't know what's wrong :stuck_out_tongue:

**Comment by TiTo-418** [comment]
The server does not start it froze on "Deleting match files..."

**Comment by twizmwazin** [comment]
@TiTo-418 That shouldn't be affected by this PR. If deleting old match files takes too long for you, it can be disabled in the config.

**Comment by TiTo-418** [comment]
@twizmwazin With an empty ranks.xml the server start normally

**Comment by iEli2tyree011** [comment]
@twizmwazin That's just the last message that is logged before the server freezes, the problem is with inheritance logic.

**Comment by TiTo-418** [comment]
I don't know if this is intended, but i can not give or remove ranks from offline players http://prntscr.com/7u1mc5

**Comment by iEli2tyree011** [comment]
@TiTo-418 The freezing issue has been solved, your ranks should work.

**Comment by TiTo-418** [comment]
@iEli2tyree011 Yes, it is fixed, thanks!

**Comment by TiTo-418** [comment]
Ok, i don't know if i removed default perms, but streamers can talk in global chat (same ranks.xml)

**Comment by iEli2tyree011** [comment]
@TiTo-418 Just because the `Streamer` rank's parent isn't `Default` doesn't mean the player doesn't have the `Default` rank, which gives the player chat permissions. Since the `Default` rank is default, the rank is given to any player when they join the game.

**Comment by TiTo-418** [comment]
@iEli2tyree011 Oh, ok. There are a way to remove it?
And, is necesary the Default parent in the Moderator Rank?

**Comment by iEli2tyree011** [comment]
@TiTo-418 Not that I can think of. And since the `Default` rank is given to all players when they join regardless of having the `Moderator` rank or not, inheritance in that case shouldn't be necessary.

**Comment by TiTo-418** [comment]
@iEli2tyree011 Ok, thanks

**Comment by iEli2tyree011** [comment]
@TiTo-418 Okay, thank you :smile:

**Comment by dentmaged** [comment]
@iEli2tyree011 Can players revoke permissions by add a ```-``` in front of a permission? I must say, this looks awesome!

**Comment by iEli2tyree011** [comment]
@dentmaged That's actually a really good way of condensing that. I'm thinking that would override any permissions received from inheritance, which would solve @TiTo-418's problem

**Comment by iEli2tyree011** [comment]
I added it so you can disable permissions for ranks, which overrides permissions gotten from inheritance and is not inherited itself. This is untested, and may not work. This is just what I have so far for the night, but it's getting late, and I'm going to go. If someone could get back to me on how this works, that would be great.

**Comment by TiTo-418** [comment]
The disabled permissions works fine.
The command /rank info isn't implemented

**Comment by Alfalik** [comment]
Could you fix #566 with a toggleable option in the ```config.yml```, like ```whitelist-staff = true```

**Comment by TiTo-418** [comment]
@Alfalik That souldn't be a toggleable option

**Comment by Pablete1234** [comment]
It would be nice if you could add a bypass-whitelist permission, or something like that (just the same way op's can bypass it)

**Comment by TiTo-418** [comment]
@Pablete1234 https://github.com/twizmwazin/CardinalPGM/issues/566

**Comment by TiTo-418** [comment]
I think the ranks branch can be removed

**Pull request closed without merging**
