### PR TITLE
Prevent observers to count towards proximity

### LINKED ISSUE #851: Observers count towards proximity
How to reproduce:
 On DTC, one player joins team read, the other one stays on obs
 /start, and as the joined player gets closer to blue's core/monument, on the scoreboard red appears first (winning team)
 as soon as the observer, goes closer to red's core than the joined player to blue, blue starts winning
 /scores also say that the team with no joined players is winning

### PR DESCRIPTION
**Pull request by Pablete1234**
fixes #851

### CODE REVIEW

**Comment by dentmaged** [comment]
You don't need to make an issue and a pull request.

**Comment by Pablete1234** [comment]
i made the issue bcos i didn't think it was that "obious" when i then looked at the code i saw the bug and i made the PR

**Comment by twizmwazin** [comment]
@dentmaged Actually I would prefer if you make an issue and a PR. Make an issue immediately, and then begin writing your fix.

**Comment by dentmaged** [comment]
@twizmwazin oh okay. I made an issue and a PR a while ago and you told me to only make a PR.

**Comment by twizmwazin** [comment]
@dentmaged perhaps that was a different circumstance. adding features an issue doesn't need to be made

**Comment by dentmaged** [comment]
@twizmwazin That was a bug fix.

**Comment by twizmwazin** [comment]
merged, thanks

**Pull request closed without merging**
