### PR TITLE
Prevent projectiles hitting yourself, fixes #855

### LINKED ISSUE #855: You can damage yourself with your arrows
Latest [versions](http://prntscr.com/8970xq)

### PR DESCRIPTION
**Pull request by Pablete1234**
It still plays the *ding* sound if you hit yourself, but it's 99.9999% less annoying than before

Note: removed the metadata as i felt it's not necesary, setting friendlyfire on the teams fixes hitting other players, it only doesn't work on yourself
Tested with 2 accounts, you can hit players in other teams, you can't hit yourself, and you can't hit your own team

### CODE REVIEW

**Comment by Prodigy4532** [comment]
You can blow your own team.

**Comment by Pablete1234** [comment]
@Prodigy4532 i belive that's controled separetly, and the map decides if it's enabled or disabled

**Comment by Pablete1234** [comment]
@Prodigy4532 https://github.com/twizmwazin/CardinalPGM/blob/master/src/main/java/in/twizmwaz/cardinal/module/modules/disableDamage/DisableDamage.java is what controls TNT, and it's not quite as good as it should be, it should handle everything here:  https://docs.oc.tc/modules/damage

**Comment by Pablete1234** [comment]
@twizmwazin opinions? it removes all the other code, but it works, and does exactly what it needs to do. other players in your same team don't get hit because team friendly fire is set to off.

**Comment by twizmwazin** [comment]
Aren't you supposed to be able to hit yourself in PGM?

**Comment by Pablete1234** [comment]
@twizmwazin not with arrows, they changed sportbukkit so that frendly fire setting on the team does not affect yourself, and in PGM for some days you could shoot yourself, but that got fixed, and this also needs a fix.

ps: this does not affect tnt, your own tnt does kill yourself

**Comment by Pablete1234** [comment]
merged

**Pull request closed without merging**
