### PR TITLE
You don't recive snowflakes destroying a wool that has been placed

### LINKED ISSUE #902: You can destroy your own wool after placed.

### PR DESCRIPTION
**Pull request by Pablete1234**
fixes #902 
(tested and works)

### CODE REVIEW

**Comment by Pablete1234** [comment]
@twizmwazin opinions?

**Comment by dentmaged** [comment]
@Pablete1234 I know this isn't directed towards me, but seems good to merge!

**Comment by twizmwazin** [comment]
This is good to merge as soon as I sit down at my computer

**Comment by twizmwazin** [comment]
merged

**Pull request closed without merging**
