### PR TITLE
Fixed color error on leaked core message

### PR DESCRIPTION
**Pull request by felipufeliu**

### CODE REVIEW

**Comment by twizmwazin** [comment]
uhh... is this correct?

**Comment by iEli2tyree011** [comment]
no, it's not http://i.imgur.com/1a8Unsb.png

**Comment by iEli2tyree011** [comment]
nvm

**Comment by twizmwazin** [comment]
http://gyazo.com/aab0fff849a7cb3970a3bbbf1a87f23c

**Pull request merged**
