### PR TITLE
Change compass name and color

### PR DESCRIPTION
**Pull request by Vixo1**

### CODE REVIEW

**Comment by CaptainElliott** [comment]
Could you make it one line?
```java
player.getInventory().setItem(0, Items.createItem(Material.COMPASS, 1, (short) 0, ChatColor.BLUE + "" + ChatColor.BOLD + "Teleport Tool");
```

**Comment by twizmwazin** [comment]
Why is this code in four places, also, localization

**Comment by ryanw-se** [comment]
Hey @Vixo1, are you able to amend your PR down to one commit or would you like me to do that for you?

**Comment by Vixo1** [comment]
I maked it one commit (Thanks @Pablete1234) but I think that this will not be necessary if #810 is implemented.

**Comment by TiTo-418** [comment]
Implemented in https://github.com/twizmwazin/CardinalPGM/commit/56b4c5b5896387ad579ea0de62f7f823b0fba813

**Comment by Pablete1234** [comment]
As @TiTo-418 said has been implemented by #933

**Pull request closed without merging**
