### PR TITLE
Fix tool repair module merging items that shouldn't merge

### PR DESCRIPTION
**Pull request by Pablete1234**
Now it literally checks that both items are exactly the same (without durability)
"toMaxDurability(1).equals(toMaxDurability(2))" Inspired by "1.toLowerCase() == 2.toLowerCase"

### CODE REVIEW

**Comment by Pablete1234** [comment]
@twizmwazin opinions on the implementation?

**Comment by twizmwazin** [comment]
Looks good, just wanna hear testing results

**Comment by Pablete1234** [comment]
when i tested personally it didnt have any problems

**Comment by twizmwazin** [comment]
merged

**Pull request closed without merging**
