### PR TITLE
update max height chat message to the one in oc.tc

### PR DESCRIPTION
**Pull request by Pablete1234**
in oc.tc it's like this:
http://gyazo.com/d837728fdaf45b020f7803710dd679ba

### CODE REVIEW

**Comment by RubeVi** [comment]
innecesary, btw

**Comment by Pablete1234** [comment]
Just why not to have it?
Alot of messages have been changed in 1.8 pgm, we can start updating cardinal ones as we see them

**Comment by twizmwazin** [comment]
@Pablete1234 I'd be willing to merge it if the commit message was better. I'm really OCN about these things. Something like "Update world height limit message" would sound better and be somewhat more descriptive.

**Comment by Pablete1234** [comment]
@twizmwazin i'm not too good at describbing, i'm more on the math side

**Comment by TiTo-418** [comment]
Can i do this?

**Comment by Pablete1234** [comment]
@TiTo-418 commit stealer ¬¬

**Comment by Pablete1234** [comment]
#746

**Comment by dentmaged** [comment]
#TiToHypocriticalCommitFarmer

**Comment by TiTo-418** [comment]
@dentmaged @Pablete1234 I love u guys <3

**Pull request closed without merging**
