### PR TITLE
Fix punishment messages.

### PR DESCRIPTION
**Pull request by felipufeliu**
http://prntscr.com/69icmh
http://gyazo.com/e2d9b7534dbd6e2456dbd691a36844bb
http://gyazo.com/c13aa7292748a8a2165840857f3159ee

### CODE REVIEW

**Comment by CaptainElliott** [comment]
just a heads up, its conventions to put commit messages in the past tense `fixed` should be `fix`

**Comment by felipufeliu** [comment]
@CaptainElliott I already changed the fixed to fix :p

**Comment by twizmwazin** [comment]
@felipufeliu the correct naming would be "Fix punishment messages"

**Comment by twizmwazin** [comment]
@felipufeliu Can you make this all one commit instead of four?

**Comment by felipufeliu** [comment]
@twizmwazin For that, I'd have to close this one and create a new one?

**Comment by twizmwazin** [comment]
@felipufeliu That works

**Pull request closed without merging**
