### PR TITLE
Add shortest commands for team commands

### PR DESCRIPTION
**Pull request by Alfalik**
I've added shortest "aliases" for team commands. Also, now the shuffle command can only be executed if the match is waiting or starting and the team change name is sent to the global channel.

Here's a test https://youtu.be/c0Q9Q1gs068

### CODE REVIEW

**Comment by dentmaged** [comment]
@Alfalik You don't need an extra class, just register TeamCommands and TeamCommands.ParentTeamCommand

**Comment by Alfalik** [comment]
@dentmaged Thanks! Didn't really know.

**Comment by Alfalik** [comment]
@twizmwazin Could you add this? For me, it's pretty useful do ```/force <player> <team>``` instead of ```/team force <player> <team>```. I also fixed shuffling teams during a match being played.

**Comment by twizmwazin** [comment]
@Alfalik Can you rebase the commit on master? After that I looks ready to merge

**Comment by Alfalik** [comment]
@twizmwazin Done!

**Pull request merged**
