### PR TITLE
Update tab header colors for authors

### PR DESCRIPTION
**Pull request by Pablete1234**
this is how it is now on oc.tc
http://gyazo.com/28edae3d60fb814e74b9b04847ceadfb

### CODE REVIEW

**Comment by CaptainElliott** [comment]
The change isn't that simple, it now uses the player's display name and their team color if they are online, including flairs, and if they are offline then make it cyan. 

Also when making changes give the commit a relevant name

**Comment by Pablete1234** [comment]
should i then open a issue and close this pull request?

**Comment by dentmaged** [comment]
@Pablete1234 I'll do the PR, if you want.

**Comment by Pablete1234** [comment]
#730 fixes what this one partially fixed

**Comment by Pablete1234** [comment]
#736

**Pull request closed without merging**
