### PR TITLE
Remove "the" from touch observers message, fixes #481

### LINKED ISSUE #481: Incorrect touch message in obs
<a href="http://imgur.com/2uzfX0b"></a>

Shoud be: [Player] damaged [objetive] for [Team]

### PR DESCRIPTION
**Pull request by Alfalik**
Since Cardinal is for scrimmages, it wont show team names as "Red Team", will be "Oklahomies" as example.

### CODE REVIEW

**Comment by AngelCasillas01** [comment]
maybe you may do this on es.xml, it.xml, ETC..

**Comment by iEli2tyree011** [comment]
This is how it is on translate.oc.tc, so we are going to keep it this way.

**Comment by Superjd10** [comment]
@iEli2tyree011  translate.oc.tc has the article "the" in english, but in spanish we don't use it.

**Comment by iEli2tyree011** [comment]
@Superjd10 Right, but in this pull request he was modifying the English translation.

**Comment by TiTo-418** [comment]
"Since Cardinal is for scrimmages, it wont show team names as "Red Team", will be "Oklahomies" as example."

**Comment by TiTo-418** [comment]
@Superjd10 En espanol si se usa, "Superjd10 dano monumento para EL equipo azul"
Pero no se diria: Superjd10 dano monumento para EL Impact

**Comment by TiTo-418** [comment]
Idea: when a team has alias, remove the "the"

**Comment by Superjd10** [comment]
@TiTo-418 That's why we didn't translated "the" in spanish, we just ignored it. Now, let's keep it on topic: I don't see why we should remove it, it's minor.

**Pull request closed without merging**
