### PR TITLE
Add WorldBorderModule

### PR DESCRIPTION
**Pull request by thomblr**
### Add WorldBorderModule
Added ability to create world borders in XML.
Not very usefull but It needs to be implemented.
_There are maybe some bugs_

### CODE REVIEW

**Comment by Pablete1234** [comment]
@iEli2tyree011 @twizmwazin opinions?
(Just saying bcos it's been 8 days...)

**Comment by TiTo-418** [comment]
@maestro34 This PR should be rebased

**Comment by twizmwazin** [comment]
I know it should be rebased, but if anyone wants to let me know how this is as-is, then I can rebase it myself if @maestro34 doesn't get around to it. If it works as expected I can merge it.

**Comment by maestro34** [comment]
If everything is good I prefer you rebase it because I'm not comfortable with it.

**Comment by twizmwazin** [comment]
If someone wants to test this, and @thomblr if you'd like to rebase it, this could get merged.

**Comment by Pablete1234** [comment]
Should be tracked in #1023

**Pull request closed without merging**
