### PR TITLE
Added global message for ready command and fixed colors

### PR DESCRIPTION
**Pull request by Alfalik**
http://gyazo.com/d6ac4d840f2273977f80015d4cb773d8

### CODE REVIEW

**Comment by CaptainElliott** [comment]
I don't know if the global message is necessary,they already see that the team has unready-ed

**Comment by Alfalik** [comment]
Its useful, you dont see/know what team is un-ready. Merge if you want.

**Comment by CaptainElliott** [comment]
The team that is not ready is broadcasted

**Comment by Alfalik** [comment]
Already know, but if you want it similar to OCN, your decision.

http://gyazo.com/7b0256242d9327a0552d0e88226492ab

**Comment by CaptainElliott** [comment]
ok, Thanks!

**Pull request merged**
