### PR TITLE
Add /statspage command

### PR DESCRIPTION
**Pull request by dentmaged**
This commit adds:
* /statistics (alias for /stats)
* /statspage (new command)
* /statisticspage (alias for /statspage)
* /reportpage (alias for /statspage)
* Formats time in statistics.html

### CODE REVIEW

**Comment by twizmwazin** [comment]
Please provide a more detailed explanation on statspage.

**Comment by dentmaged** [comment]
@twizmwazin Sorry! What the command does, it is displays the link to the stat page (uploaded when the game ends). I find it rather useful for tournaments and that sort of thing.

**Comment by twizmwazin** [comment]
@dentmaged Will it display the link if the page is not yet uploaded?

**Comment by dentmaged** [comment]
@twizmwazin Yep!

**Comment by twizmwazin** [comment]
@dentmaged I'm not sure I like that, it will lead to a ton of 404 requests.

**Comment by dentmaged** [comment]
@twizmwazin How so? It would have to be uploaded, I check if the game hasn't ended and if html.upload  is enabled

**Comment by iEli2tyree011** [comment]
@dentmaged What happens if they run the command in between the end of the match and when the page is successfully uploaded?

**Comment by SungMatt** [comment]
@iEli2tyree011 Isn't the server effectively frozen during this period of time?

**Comment by twizmwazin** [comment]
@SungMatt No, it is on its own thread.

**Comment by dentmaged** [comment]
Bump.

**Pull request closed without merging**
