### PR TITLE
Implement fancy tab

### PR DESCRIPTION
**Pull request by Pablete1234**
This fancy tab, uses teams to order players, the other one used a set of 80 players, and had to remove and add them to be able to change skin in a position, with the new system that doesn't need to be done like that

PS: this is not ready for testing yet! it's really buggy atm

### CODE REVIEW

**Comment by TiTo-418** [comment]
Could you merge this one the other and keep working on this one?

**Comment by Pablete1234** [comment]
@TiTo-418 i don't consider the other one finnished, some players i know have problems with it

**Comment by xFracTV** [comment]
And, why not merge the other and fix the bugs with this PR

**Comment by Pablete1234** [comment]
@xFracTV this is not a "fix" of the other one, this uses a whole new system, that's why it has it's own PR, the other system works quite nicely(isn't 100% finnished), but has some limitations, that this system should remove, if at the end, i can't get this one to work as i expect, i will finnish the old one, and forget about this one, that's why i want to keep them separate

**Comment by Pablete1234** [comment]
Updated, this version is now functional, and i would like some feedback

**Comment by Pablete1234** [comment]
@twizmwazin take a look at formatting, this is pretty much ready to merge

**Comment by SwiftGFX** [comment]
:+1:

**Comment by Pablete1234** [comment]
@twizmwazin fixed getBiggestTeamSize, anything else that should be done?

**Comment by twizmwazin** [comment]
looks good, go ahead and merge

**Comment by Pablete1234** [comment]
merged

**Pull request closed without merging**
