### PR TITLE
Don't 'showl' a hill and make 'HillObjective' a tasked module

### PR DESCRIPTION
**Pull request by dentmaged**
Begin work on KOTH.

### CODE REVIEW

**Comment by twizmwazin** [comment]
I feel like this is desperation for a commit, but ok

**Comment by dentmaged** [comment]
@twizmwazin If you want to 'showl' a hill, feel free to revert my commit. I am not in any desperation for a commit.

**Comment by twizmwazin** [comment]
@dentmaged un huh

**Comment by dentmaged** [comment]
@twizmwazin ?

**Pull request merged**
