### PR TITLE
Some changes to es.xml

### PR DESCRIPTION
**Pull request by AngelCasillas01**

### CODE REVIEW

**Comment by twizmwazin** [comment]
Can some Spanish speakers provide feedback?

**Comment by ElFlambMC** [comment]
Good translate

**Comment by TiTo-418** [comment]
+1

**Comment by Prodigy4532** [comment]
+1

**Comment by Superjd10** [comment]
I agree with line 11, I don't know why it was translated here as "sobreescribir".

About libe 63, I may disagree. We did our best on the Crowdin project, if we wanna change it, we may discuss there: https://crowdin.com/translate/ocn-plugins/42/en-es#839 (translated almost 1 year ago).

**Comment by TiTo-418** [comment]
It's the same, "Partida no válida" and "Partida inválida" are synonymous

**Comment by AngelCasillas01** [comment]
@TiTo-418  but almost all translate on this xml says invalida :p @twizmwazin merge this if you want

**Comment by TiTo-418** [comment]
@AngelCasillas01 yeah, it's true, merge this

**Comment by Carlos934** [comment]
+1

**Comment by AngelCasillas01** [comment]
😒

**Pull request closed without merging**
