### PR TITLE
Add kills and deaths stats

### PR DESCRIPTION
**Pull request by Pablete1234**
You can /toggle stats to toggle between sidebar, actionbar, and bossbar(I personally don't like this one).

A pic of how all of 3 at once would look like:
Stats

Note: don't expect this to be a feature of cardinal right away, for the time being it's here just to be tested and to see players' opinions

### CODE REVIEW

**Comment by SungMatt** [comment]
Woohoo, /stats is back!!

**Comment by Pablete1234** [comment]
@SungMatt but this time it's 200% better than a command :P

**Comment by SungMatt** [comment]
The group that I play with would be very happy to see this come back, since it disappeared a year ago!

**Comment by Pablete1234** [comment]
@twizmwazin fixed all the hashmaps

**Comment by iPGz** [comment]
Great idea, love the implementation :tada:

**Comment by Pablete1234** [comment]
@iPGz how would it not be a great idea if it was yours!? nice to know you like the way i implemented it :P

**Comment by SungMatt** [comment]
Tested with myself and a friend of mine, sidebar is working as intended! Will be playtesting more today, as I get more people.

**Comment by Pablete1234** [comment]
@SungMatt i'll update it to 1.10

**Comment by SungMatt** [comment]
@Pablete1234 Tested it, there appears to be an issue in TDM where scores do not increment properly. Upon Team 1 player death via being killed by a Team 2 player, Team 2's score increments by 1 (Correct behaviour) but Team 1's score decreases by 1 (Incorrect behaviour) 

screen shot 2016-06-12 at 1 13 01 pm

**Comment by Pablete1234** [comment]
merged

**Pull request closed without merging**
