### PR TITLE
Safer module builder loading

### PR DESCRIPTION
**Pull request by CaptainElliott**
Removes the unsafe and bad raw type issue. Should work fine haven't done extensive testing

### CODE REVIEW

**Comment by Pablete1234** [comment]
@CaptainElliott i thought you were dead

**Comment by CaptainElliott** [comment]
I came back its ok... 

Regarding PR just read through it as I did it in a rush as I needed to leave my house, I accidentally instantiated the set in the variable declaration instead of the contructor. 

I also think I might rename the method to something lie addBuilders.

In addition now that this removes the raw type array and replaces it with a parameterlized set I guess the list could me removed? 

That all needs to be done before this can even be considered to merge.

**Comment by CaptainElliott** [comment]
Probably should have waited to get home to do this PR, anyway also just wanted to add some more description to the point of the PR. 

It removes the unsafe raw type sclera room for classes which could throw a ClassCastException at runtime if a mistake was made in the list of builders resulting it to contain a non builder class. Instead with the parameterlized type it will give a warning at compile time - which is obviously much better.

Sorry if there's any mistakes in these comments - on phone

**Comment by twizmwazin** [comment]
I'm not a fan of wildcard imports.

**Comment by CaptainElliott** [comment]
@twizmwazin will fix when I'm back home

**Comment by CaptainElliott** [comment]
@twizmwazin done, can squash if you think this is all ok

**Comment by CaptainElliott** [comment]
@twizmwazin all squashed for ya

**Comment by CaptainElliott** [comment]
@twizmwazin merge?

**Comment by twizmwazin** [comment]
done

**Pull request closed without merging**
