### PR TITLE
Implement fancy tab

### PR DESCRIPTION
**Pull request by Pablete1234**
The feature is fully working except that it's missing skins, everything else works, even tho i would like to remove the code from the header module, and create it's own module, also some events that update it may be missing

PS: any help implementing skins will be nice

### CODE REVIEW

**Comment by TiTo-418** [comment]
/team alias doesn't change the name in the tab

There are others bugs like this one http://imgur.com/09Eygy1

**Comment by Pablete1234** [comment]
@TiTo-418 i already fixed the team join updating

**Comment by Eudaldca** [comment]
@Pablete1234 Minor, but some tab UUID's match real player's UUID.

**Comment by Pablete1234** [comment]
how should i go arround it?

**Comment by Pablete1234** [comment]
This should be ready to use in all servers, but may have issues if the server has +70 players (even tho it shouldn't)

**Comment by Pablete1234** [comment]
Only known bug atm is that hats don't show up (skins show up, but not the overlay)

**Comment by Eudaldca** [comment]
Great job @Pablete1234! :clap:

**Comment by dentmaged** [comment]
@Pablete1234 look at this: http://dentmaged.github.io/docs/sportbukkit/org/bukkit/Skin.html

**Comment by Pablete1234** [comment]
@xFracTV already known bug, and i have a patch for it, i'll push it later

**Comment by Pablete1234** [comment]
@xFracTV fixed

**Comment by twizmwazin** [comment]
Made a few notes on formatting, this is looking really great though.

**Comment by xFracTV** [comment]
when you use " ". Team name does not appear

**Comment by Pablete1234** [comment]
I knew you could "/team alias blue \u00A74Red" and it would use unicode values, didn't think quotes would give problems
@twizmwazin what is the best way i could escape that?
```
L329: IChatBaseComponent.ChatSerializer.a("{text:\"" + displayName + "\"}")
```
means:
```
{text:" + whatever + "}
```

**Comment by twizmwazin** [comment]
I think you figured it out. Alternately, we could prohibit certain chars from being used in team names

**Comment by Pablete1234** [comment]
I don't think we need to prohibit any characters, i only need to escape the characters that go into the text, my question is, what is the best method to escape a string?

**Comment by Pablete1234** [comment]
I don't think we need to prohibit any characters, i only need to escape the characters that go into the text, my question is, what is the best method to escape a string?

**Comment by twizmwazin** [comment]
Backslashes are the only way to escape strings

**Comment by Pablete1234** [comment]
I know that, but what method/library/util/whatever does it with all chararters that need it?

**Comment by CaptainElliott** [comment]
@Pablete1234 try out apache commons https://commons.apache.org/proper/commons-lang/javadocs/api-2.6/org/apache/commons/lang/StringEscapeUtils.html#escapeJava(java.lang.String)

**Comment by Pablete1234** [comment]
moved on to fancy tab V2 #956

**Pull request closed without merging**
