### PR TITLE
Fix rightclick with book

### PR DESCRIPTION
**Pull request by Pablete1234**
ATM in cardinal in observers, if you are holding the book, you can interact with the world, for example, opening doors, tirggering buttons, and changig repeater delay

### CODE REVIEW

**Comment by CaptainElliott** [comment]
Why not just prevent interaction all together instead of having a hard coded list of blacklsited blocks?

**Comment by Pablete1234** [comment]
@CaptainElliott because then you can't open the book

**Comment by twizmwazin** [comment]
Is it possible to cancel the event and then show the player the book? That just seems like a better solution to me.

**Comment by Pablete1234** [comment]
@twizmwazin maybe it is (kinda like what you do with inventories) but i'm not sure, specially i'm not sure if i can show the contents properly, because they are not coded in atm

**Comment by CaptainElliott** [comment]
Try using the `BlockPhysicsEvent` I'm pretty sure that is called when things like this happen

**Comment by Pablete1234** [comment]
@CaptainElliott you can know that a block changed, but  you don't know who caused it, and therefore you can't cancel it if it's an obs doing it

**Comment by Pablete1234** [comment]
@twizmwazin you can merge this already, it's fixed

**Comment by twizmwazin** [comment]
Is Craftbukkit code the only way to fix this?

**Comment by Pablete1234** [comment]
@twizmwazin it's the only way to "openInventory(Type.Book)", usually if you rightclick a button/trapdoor/whatever the "opening book interface" event is not triggered, and CraftBukkit i belive it's the only way to trigger it

**Comment by twizmwazin** [comment]
merged

**Pull request closed without merging**
