### PR TITLE
Allow for multiple repositories to store maps

### PR DESCRIPTION
**Pull request by dentmaged**
All in the title!

### CODE REVIEW

**Comment by Pablete1234** [comment]
do i have to include each repo? or should any folder that's not considered a map be a new repo?

**Comment by dentmaged** [comment]
@Pablete1234 You have to include it manually.

**Comment by Pablete1234** [comment]
is it possible to make it automatic?
just if a folder doesn't have the needed stuff (region,xml and level.dat), it gets added as a new repo

**Comment by dentmaged** [comment]
@Pablete1234 Some people would want a folder to put WIP maps in, I'm not too sure about this.

**Comment by Pablete1234** [comment]
look at maos.oc.tc, no one would be willing to add all paths, it's easier to block some directories

- repo: maps
 -exclude:
   - maps/other/testing

**Comment by dentmaged** [comment]
@Pablete1234 That isn't valid YAML, but I get the point. I'll see what @twizmwazin or @iEli2tyree011 think about this.

**Comment by Pablete1234** [comment]
it didnt format properly, it's supposed to be in a different line

**Comment by Pablete1234** [comment]
@dentmaged how many pages of maps do you have?

**Comment by dentmaged** [comment]
@Pablete1234 10

**Comment by Pablete1234** [comment]
i have 22... and i am willing to sort them in the same tree maps.oc.tc has
and adding maps/ctw/standard/, for ctw, dtc, tourneys etc etc...

**Comment by dentmaged** [comment]
@twizmwazin Done!

**Comment by Pablete1234** [comment]
this new commit uses any sub-folder that's not a map as a repo?

**Comment by twizmwazin** [comment]
@dentmaged Does this search folders recursively, or does it only search specified folders? I feel a good implementation should have the following:

-Automatically search all specified repository directories, recursively
-Allow the repositories to be over a network (more optional)
-Support a per-repository config, optionally located at each level in the repository, to disable certain directories from being searched, or only enable certain repositories to be searched. I'd prefer something not-YAML here, but if that is all you know how to work with, I guess it could work if implemented well.

**Comment by dentmaged** [comment]
@twizmwazin For point 2, do you mean Got integration? I tried that with Cardinal+ and it didn't work :\

Good ideas though! I'll begin work tomorrow!

**Comment by dentmaged** [comment]
Whopps...

**Comment by twizmwazin** [comment]
Leave this open if you plan on working on it. for 2 I was thinking more about HTTP & FTP

**Comment by Pablete1234** [comment]
@twizmwazin point 1 and 4 are the ones i would like the most, like just /repo /maps/other/tourney/HouseOfCores and you can set the sv to tourney-mode

**Comment by dentmaged** [comment]
@Pablete1234 Good luck implementing that, last time I did that on my edit of Cardinal, I broke it... :\ I really should have used Git and commited so I could rollback!

**Comment by dentmaged** [comment]
@twizmwazin Done!

**Comment by Pablete1234** [comment]
What's the state of this atm? Does it search folders recursively? and i guess http and ftp is not done right?

**Comment by TiTo-418** [comment]
@Pablete1234 Be patient...
PD: Congrats for the caps!

**Comment by Pablete1234** [comment]
@TiTo-418 I was just asking...
PD: ¬¬

**Comment by dentmaged** [comment]
Closing as this has a bug and I don't know how to fix it. May reopen later.

**Comment by ryanw-se** [comment]
@dentmaged Care to share what the bug is, instead of just closing this?

**Comment by Pablete1234** [comment]
@dentmaged I think this really needs to be implemented, I also think you should try to make this into cardinal

**Comment by dentmaged** [comment]
@ryanw-se Includes are broken

**Comment by twizmwazin** [comment]
Better idea

**Comment by dentmaged** [comment]
@twizmwazin Thank you!

**Comment by dentmaged** [comment]
Remove the ```WIP``` tag please.

**Comment by dentmaged** [comment]
@Pablete1234 Please remove the `WIP` tag.

**Pull request closed without merging**
