### PR TITLE
Added README stuff

### PR DESCRIPTION
**Pull request by AngelCasillas01**

### CODE REVIEW

**Comment by AngelCasillas01** [comment]
@twizmwazin i is fine now?

**Comment by twizmwazin** [comment]
@AngelCasillas01 There are a number of grammatical errors.

**Comment by CoWinkKeyDinkInc** [comment]
There are two repetitive statements in line 25 and 26, telling you how to submit a good pull request twice.
The sentence in 22 does not have a space between your and log and also it should say the log files can be found IN your log folder in your server file.

**Comment by AngelCasillas01** [comment]
@twizmwazin  and now?

**Comment by twizmwazin** [comment]
@AngelCasillas01 Still grammar errors.

**Comment by SungMatt** [comment]
@AngelCasillas01 I put the part on issue reporting in **bold** because the issue tracker is recieving a lot of non-constructive issues. The issue tracker was meant for bugs, and not that much on missing modules or for people who need technical help. As such I have done up command help in the wiki, so that @twizmwazin and the team don't have to close these non-constructive issues.

**Comment by twizmwazin** [comment]
@SungMatt Thanks for the clarification.

**Comment by AngelCasillas01** [comment]
@SungMatt They should read it anyway, however it's a good idea, why not adding more detailed instructions

**Comment by AngelCasillas01** [comment]
@twizmwazin ?

**Comment by twizmwazin** [comment]
I don't think this adds anything important. Sorry

**Comment by AngelCasillas01** [comment]
@twizmwazin i only adddirect links to IntelliJ and Eclipe download, can i just add that?

**Comment by AngelCasillas01** [comment]
@Edit: Love iPad's keyboard (sarcasm)

**Comment by twizmwazin** [comment]
@AngelCasillas01 I think anyone who should contribute can use google.

**Comment by AngelCasillas01** [comment]
@twizmwazin and the new issue line?

**Comment by twizmwazin** [comment]
@AngelCasillas01 You added links, told people to use pastebin, and it was riddled with grammatical errors.

**Comment by SungMatt** [comment]
@AngelCasillas01 I believe if we keep development details to people who understand it, we can reduce non-constructive code edits. If one has learnt code development, he/she should know what an IDE is. 

Currently Cardinal is not for public release, it is in alpha. We need to let the people who want to test Cardinal to know how to use it, to help identify relevant and important issues.

**Pull request closed without merging**
