### PR TITLE
Fix wither dissapearing when health is too low

### PR DESCRIPTION
**Pull request by Pablete1234**
I hope this fixes the issue
I didn't test this
(Maven can't build because of a dependency issue)

### CODE REVIEW

**Comment by twizmwazin** [comment]
You should be able to build now, test it when you can.

**Comment by Pablete1234** [comment]
@twizmwazin i'll be away from home 3 days, if someone else can test this it would be nice

**Comment by dentmaged** [comment]
@twizmwazin Can you restart the build? If not, @Pablete1234 can just ```git commit -m "Fix wither disappearing when health is too low" --amend```, making sure there are no new additions.

**Comment by Pablete1234** [comment]
@dentmaged I did what you said, but there is still some dependency that doesn't work
@twizmwazin tell me when cardinal should build again, and i'll re-amend it

**Comment by dentmaged** [comment]
@Pablete1234 oh okay!
@twizmwazin Why don't we try to downgrade the command framework and see if that fixes the problem?

**Comment by twizmwazin** [comment]
@dentmaged The issue isn't the version of the framework, the issue is the maven repo was down. All seems to be resolved.

**Comment by Pablete1234** [comment]
@twizmwazin re-ammended the commit, still has issues

**Comment by Pablete1234** [comment]
Tested with @twizmwazin and works

**Comment by twizmwazin** [comment]
merged

**Pull request closed without merging**
