### PR TITLE
Re-write cancel command

### PR DESCRIPTION
**Pull request by Alfalik**
This pull request just clarify what countdowns are cancelled, and also, make messages more clearer.

### CODE REVIEW

**Comment by twizmwazin** [comment]
Looks good at first glance, @iEli2tyree011

**Comment by Alfalik** [comment]
Oops! My mouse is the guilty

**Comment by twizmwazin** [comment]
Few things from testing:
 - An exception is thrown if there is no timer to cancel.
 - You make the cancel messages look like warning messages, they aren't.
 - A wording thing, the map cycles, not the match.

**Comment by Alfalik** [comment]
@twizmwazin First, thanks for testing. Now:

+ The exception has been solved.
+ Removed the warning
+ Changed the message, thanks for the correction

**Comment by twizmwazin** [comment]
Going to close this as I don't think it is still relevant. Let me know if I am mistaken.

**Pull request closed without merging**
