### PR TITLE
Add observer book

### PR DESCRIPTION
**Pull request by dentmaged**
It works but I don't know why there are ten pages, if somebody knows please feel free to make a pull request!
Book

### CODE REVIEW

**Comment by CaptainElliott** [comment]
I don't see a reason to have a module for it, just give them a book in the observer nodule by using this exisdting utility https://github.com/twizmwazin/CardinalPGM/blob/master/src/main/java/in/twizmwaz/cardinal/util/ItemUtils.java#L28
Also there 10 pages because you created ten pages....

**Comment by dentmaged** [comment]
@CaptainElliott Localization? and surely https://github.com/twizmwazin/CardinalPGM/blob/9ab0aa4639bae818c471e47f042bfc885b63ac4b/src/main/java/in/twizmwaz/cardinal/module/modules/bookModule/BookModule.java#L36 would skip that entry?

**Comment by CaptainElliott** [comment]
why are you continuing if the page is null? you want to break

**Comment by dentmaged** [comment]
Commit amended

Anyway, @CaptainElliott I am an idiot! Getting my statements mixed up!

**Comment by CaptainElliott** [comment]
I don't see why you need to create the other 10 pages for localization., just make one and use JDOM to iterate through all of the pages so it can be updated dynamically

**Comment by dentmaged** [comment]
@CaptainElliott It's what @twizmwazin wanted, unless if he has changed his mind!

**Comment by twizmwazin** [comment]
@dentmaged I like Elliott's way

**Comment by iEli2tyree011** [comment]
@twizmwazin Agreed, this method is too hard-coded.

**Comment by dentmaged** [comment]
@iEli2tyree011 @twizmwazin Okay! I'll redo it.

**Comment by AngelCasillas01** [comment]
@dentmaged  This is the reason why you have 10 pages.
`BOOK_PAGE_1("book.page1"),
BOOK_PAGE_2("book.page2"),
BOOK_PAGE_3("book.page3"),
BOOK_PAGE_4("book.page4"),
BOOK_PAGE_5("book.page5"),
BOOK_PAGE_6("book.page6"),
 BOOK_PAGE_7("book.page7"),
BOOK_PAGE_8("book.page8"),
BOOK_PAGE_9("book.page9"),
BOOK_PAGE_10("book.page10"),`

What you need to do is remove one per line until you let only `BOOK_PAGE_1("book.page1")`

**Comment by dentmaged** [comment]
@AngelCasillas01 If you read the code, you would see that it checks the page is null or "", but that doesn't work.

**Comment by dentmaged** [comment]
I think I know a better way to do this! Thanks anyway for all your help!

**Pull request closed without merging**
