### PR TITLE
Updated es.xml

### PR DESCRIPTION
**Pull request by Arhlex**
I'm spanish and I have corrected some translations.

### CODE REVIEW

**Comment by twizmwazin** [comment]
Before I merge this, if a few other people could read through and give this a thumbs up, that would be appreciated.

**Comment by Rafitamolin** [comment]
I don't think this should be merged. Translations are ok at the moment, he only changed some words to synonyms, and added some unnecessary words. I only agree changing <noShuffle>.

**Comment by twizmwazin** [comment]
@Alfalik @Superjd10 Could you guys give me your opinion of Arhlex's changes?

**Comment by Superjd10** [comment]
@twizmwazin Many grammar mistakes. If he wanna suggest something different, he should go to the OCN Crowdin project, there we discuss changes and anything related with the translations of the plugin (translations that I hear you are using for Cardinal too)

**Comment by twizmwazin** [comment]
@Superjd10 Thanks

**Pull request closed without merging**
