### PR TITLE
Update fr.xml

### PR DESCRIPTION
**Pull request by thomblr**
Some friends and I worked on the fr.xml with the CrowndIn help.

### CODE REVIEW

**Comment by unixfox** [comment]
Assez littéral comme traduction.

**Comment by thomblr** [comment]
@twizmwazin Maybe you can do something with this ?

**Comment by twizmwazin** [comment]
For language updates, because the only language I am fluent in is English, I prefer for users fluent in that language to give their feedback. The only comment on this was a negative one. @unixfox If you think this is worth merging, just let me know, and I'll be happy to do that.

**Comment by twizmwazin** [comment]
Also, @thomblr you deleted the repository this is sourced from, which will make it difficult for me to merge this.

**Comment by thomblr** [comment]
@twizmwazin So I need to remake another pull request and close this one ?
Btw, unixfox and I are friends and we updated the messages after his message.

**Comment by Pablete1234** [comment]
@thomblr if you delete the repository the pr's is sourced from, you will need to open a new one

**Comment by twizmwazin** [comment]
You shouldn't be making another PR, just force push to the branch to update it. Although you deleted the repo which will make it harder for you.

**Pull request closed without merging**
