### PR TITLE
Update inventory viewer

### LINKED ISSUE #894: Fake inventory not updated
Old: http://prntscr.com/8kjvdj
New: http://prntscr.com/8kjux4

### PR DESCRIPTION
**Pull request by Pablete1234**
Fixes #894

### CODE REVIEW

**Comment by twizmwazin** [comment]
Wildcard

**Comment by Pablete1234** [comment]
@twizmwazin blame it on intellij

**Comment by twizmwazin** [comment]
No. Intellij has settings. Use them.

**Comment by Pablete1234** [comment]
@twizmwazin bad default configs

**Comment by twizmwazin** [comment]
merged

**Pull request closed without merging**
