### PR TITLE
Improve how invalid SportBukkit versions are handled

### PR DESCRIPTION
**Pull request by ryanwarsaw**
This is a quick fix for how invalid SportBukkit versions are handled. Instead of sending a bunch of errors, it should instead send them a message that they are using a invalid version of SportBukkit, and give them information on what the correct version would be. It then disables the plugin to prevent any further issues. This hasn't been tested yet, but is fairly simple so its presumed to be working.

### CODE REVIEW

**Comment by CaptainElliott** [comment]
You might want to do `contains.1_8` because there are other 1.8 versions that will be released

**Comment by ryanwarsaw** [comment]
@CaptainElliott I didn't realize I did that, I will fix it later tonight.

**Comment by twizmwazin** [comment]
If this is going to be merged, I want to have a sportbukkit check as well, to prevent users from attempting to load it on craftbukkit & spigot.

**Comment by ryanwarsaw** [comment]
@twizmwazin This is just a quick fix, although I have no doubts you could easily code that if you wanted too :)

**Comment by ryanwarsaw** [comment]
Closed, as this feature is presumed to be added when a SportBukkit check is implemented.

**Pull request closed without merging**
